package com.clock.livewallpaper.viewUtils;

import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.Typeface;
import android.os.BatteryManager;
import android.os.Build;
import android.text.TextPaint;
import android.util.AttributeSet;
import android.view.View;
import androidx.core.view.InputDeviceCompat;

import com.clock.livewallpaper.R;
import com.clock.livewallpaper.utils.TinyDB;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;



public class SmartClockPreview extends View {
    float Digital_time_Colon_X_offset;
    float Digital_time_Colon_Y_offset;
    float Digital_time_Hours_X_offset;
    float Digital_time_Hours_Y_offset;
    float Digital_time_Mintues_X_offset;
    float Digital_time_Mintues_Y_offset;
    private Bitmap background_round;
    Context context;
    private Calendar mCalendar;
    private Paint mPaintDigital_time_Colon;
    private Paint mPaintDigital_time_Hour;
    private Paint mPaintDigital_time_Min;
    private Paint mPaint_date;
    private Paint mPaint_date1;
    private Paint mPaint_date2;
    private Bitmap scaledbackground_round;
    private Paint scaledmFilterPaint;
    private int t12hours;
    TinyDB tinyDB;
    private int twntmintues;
    private String used12hours;
    private String usedtwntymintues;
    private int sizeScaled = -1;
    private String useddate = "";
    private String usedmonth = "MM";
    private String usedweekday = "DD";
    private int textClockPosition = 10;


    private float f204x = 200.0f;


    private float f205y = 200.0f;
    private int radius = 800;
    private String[] stringsDays = {"SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"};
    private int colorpref = -1;

    public int getRadius() {
        return this.radius;
    }

    public void setRadius(int i) {
        this.radius = i;
    }

    public SmartClockPreview(Context context) {
        super(context);
        this.tinyDB = new TinyDB(context);
        this.context = context;
        init();
        config(this.f204x, this.f205y, this.radius);
    }

    public SmartClockPreview(Context context, AttributeSet attributeSet) {
        super(context, attributeSet);
        this.tinyDB = new TinyDB(context);
        this.context = context;
        init();
        config(this.f204x, this.f205y, this.radius);
    }

    public void config(float f, float f2, int i) {
        this.f204x = f;
        this.f205y = f2;
        this.radius = i / 2;
        if (i != this.sizeScaled) {
            init();
        }
        invalidate();
    }

    @Override
    public void onDraw(Canvas canvas) {
        super.onDraw(canvas);
        drawBg(canvas);
    }

    public int getTextClockPosition() {
        return this.textClockPosition;
    }

    public void setTextClockPosition(int i) {
        this.textClockPosition = i;
        init();
        invalidate();
    }

    public void init() {
        Calendar instance = Calendar.getInstance();
        this.mCalendar = instance;
        instance.setTimeInMillis(System.currentTimeMillis());
        Paint paint = new Paint();
        this.scaledmFilterPaint = paint;
        paint.setFilterBitmap(true);
        TextPaint textPaint = new TextPaint();
        this.mPaint_date = textPaint;
        textPaint.setColor(this.colorpref);
        this.mPaint_date.setTextAlign(Paint.Align.CENTER);
        this.mPaint_date.setAntiAlias(true);
        TextPaint textPaint2 = new TextPaint();
        this.mPaint_date1 = textPaint2;
        textPaint2.setColor(this.colorpref);
        this.mPaint_date1.setTextAlign(Paint.Align.CENTER);
        this.mPaint_date1.setAntiAlias(true);
        TextPaint textPaint3 = new TextPaint();
        this.mPaint_date2 = textPaint3;
        textPaint3.setColor(this.colorpref);
        this.mPaint_date2.setTextAlign(Paint.Align.CENTER);
        this.mPaint_date2.setAntiAlias(true);
        TextPaint textPaint4 = new TextPaint();
        this.mPaintDigital_time_Hour = textPaint4;
        textPaint4.setColor(this.colorpref);
        this.mPaintDigital_time_Hour.setTextAlign(Paint.Align.CENTER);
        this.mPaintDigital_time_Hour.setAntiAlias(true);
        TextPaint textPaint5 = new TextPaint();
        this.mPaintDigital_time_Min = textPaint5;
        textPaint5.setColor(InputDeviceCompat.SOURCE_ANY);
        this.mPaintDigital_time_Min.setTextAlign(Paint.Align.CENTER);
        this.mPaintDigital_time_Min.setAntiAlias(true);
        TextPaint textPaint6 = new TextPaint();
        this.mPaintDigital_time_Colon = textPaint6;
        textPaint6.setColor(InputDeviceCompat.SOURCE_ANY);
        this.mPaintDigital_time_Colon.setTextAlign(Paint.Align.CENTER);
        this.mPaintDigital_time_Colon.setAntiAlias(true);
        setTextFace();
    }

    private void drawBg(Canvas canvas) {
        canvas.drawColor(0);
        Bitmap bitmap = this.scaledbackground_round;
        if (bitmap != null) {
            float f = this.f204x;
            int i = this.radius;
            canvas.drawBitmap(bitmap, f - (((float) i) / 2.0f), this.f205y - (((float) i) / 2.0f), (Paint) null);
        }
        Calendar instance = Calendar.getInstance();
        this.mCalendar = instance;
        this.t12hours = instance.get(10);
        this.used12hours = this.t12hours + "";
        this.twntmintues = this.mCalendar.get(12);
        this.usedtwntymintues = this.twntmintues + "";
        int i2 = this.t12hours;
        if (i2 == 0) {
            this.used12hours = "12";
        }
        if (i2 < 10) {
            this.used12hours = "0" + this.t12hours;
        }
        if (this.twntmintues < 10) {
            this.usedtwntymintues = "0" + this.twntmintues;
        }
        if (this.twntmintues < 10) {
            this.usedtwntymintues = "0" + this.twntmintues;
        }
        if (this.t12hours == 0) {
            this.used12hours = "12";
        }
        switch (this.textClockPosition) {
            case 0:
                Paint paint = this.mPaintDigital_time_Min;
                double d = (double) this.radius;
                Double.isNaN(d);
                paint.setTextSize((float) (d * 0.2d));
                Paint paint2 = this.mPaintDigital_time_Hour;
                double d2 = (double) this.radius;
                Double.isNaN(d2);
                paint2.setTextSize((float) (d2 * 0.2d));
                float f2 = this.f204x;
                double d3 = (double) f2;
                int i3 = this.radius;
                double d4 = (double) i3;
                Double.isNaN(d4);
                Double.isNaN(d3);
                float f3 = (float) (d3 - (d4 * 0.16d));
                this.Digital_time_Hours_X_offset = f3;
                float f4 = this.f205y;
                this.Digital_time_Hours_Y_offset = f4;
                this.Digital_time_Colon_X_offset = f2;
                double d5 = (double) f4;
                double d6 = (double) i3;
                Double.isNaN(d6);
                Double.isNaN(d5);
                this.Digital_time_Colon_Y_offset = (float) (d5 - (d6 * 0.02d));
                double d7 = (double) f2;
                double d8 = (double) i3;
                Double.isNaN(d8);
                Double.isNaN(d7);
                this.Digital_time_Mintues_X_offset = (float) (d7 + (d8 * 0.16d));
                this.Digital_time_Mintues_Y_offset = f4;
                canvas.drawText(this.used12hours, f3, f4, this.mPaintDigital_time_Hour);
                canvas.drawText(":", this.Digital_time_Colon_X_offset, this.Digital_time_Colon_Y_offset, this.mPaintDigital_time_Min);
                canvas.drawText(this.usedtwntymintues, this.Digital_time_Mintues_X_offset, this.Digital_time_Mintues_Y_offset, this.mPaintDigital_time_Min);
                Calendar_data();
                Paint paint3 = this.mPaint_date;
                double d9 = (double) this.radius;
                Double.isNaN(d9);
                paint3.setTextSize((float) (d9 * 0.08d));
                Paint paint4 = this.mPaint_date1;
                double d10 = (double) this.radius;
                Double.isNaN(d10);
                paint4.setTextSize((float) (d10 * 0.08d));
                Paint paint5 = this.mPaint_date2;
                double d11 = (double) this.radius;
                Double.isNaN(d11);
                paint5.setTextSize((float) (d11 * 0.08d));
                String str = this.usedweekday;
                double d12 = (double) this.f204x;
                int i4 = this.radius;
                double d13 = (double) i4;
                Double.isNaN(d13);
                Double.isNaN(d12);
                double d14 = (double) this.f205y;
                double d15 = (double) i4;
                Double.isNaN(d15);
                Double.isNaN(d14);
                canvas.drawText(str, (float) (d12 - (d13 * 0.18d)), (float) (d14 + (d15 * 0.12d)), this.mPaint_date);
                String str2 = this.useddate;
                float f5 = this.f204x;
                double d16 = (double) this.f205y;
                double d17 = (double) this.radius;
                Double.isNaN(d17);
                Double.isNaN(d16);
                canvas.drawText(str2, f5, (float) (d16 + (d17 * 0.12d)), this.mPaint_date1);
                String str3 = this.usedmonth;
                double d18 = (double) this.f204x;
                int i5 = this.radius;
                double d19 = (double) i5;
                Double.isNaN(d19);
                Double.isNaN(d18);
                double d20 = (double) this.f205y;
                double d21 = (double) i5;
                Double.isNaN(d21);
                Double.isNaN(d20);
                canvas.drawText(str3, (float) (d18 + (d19 * 0.17d)), (float) (d20 + (d21 * 0.12d)), this.mPaint_date2);
                return;
            case 1:
                Paint paint6 = this.mPaintDigital_time_Min;
                double d22 = (double) this.radius;
                Double.isNaN(d22);
                paint6.setTextSize((float) (d22 * 0.13d));
                Paint paint7 = this.mPaintDigital_time_Hour;
                double d23 = (double) this.radius;
                Double.isNaN(d23);
                paint7.setTextSize((float) (d23 * 0.22d));
                Paint paint8 = this.mPaintDigital_time_Colon;
                double d24 = (double) this.radius;
                Double.isNaN(d24);
                paint8.setTextSize((float) (d24 * 0.04d));
                float f6 = this.f204x;
                double d25 = (double) f6;
                int i6 = this.radius;
                double d26 = (double) i6;
                Double.isNaN(d26);
                Double.isNaN(d25);
                this.Digital_time_Hours_X_offset = (float) (d25 - (d26 * 0.1d));
                float f7 = this.f205y;
                double d27 = (double) f7;
                double d28 = (double) i6;
                Double.isNaN(d28);
                Double.isNaN(d27);
                this.Digital_time_Hours_Y_offset = (float) (d27 + (d28 * 0.05d));
                double d29 = (double) f6;
                double d30 = (double) i6;
                Double.isNaN(d30);
                Double.isNaN(d29);
                this.Digital_time_Mintues_X_offset = (float) (d29 + (d30 * 0.11d));
                double d31 = (double) f7;
                double d32 = (double) i6;
                Double.isNaN(d32);
                Double.isNaN(d31);
                this.Digital_time_Mintues_Y_offset = (float) (d31 + (d32 * 0.0d));
                double d33 = (double) f6;
                double d34 = (double) i6;
                Double.isNaN(d34);
                Double.isNaN(d33);
                this.Digital_time_Colon_X_offset = (float) (d33 + (d34 * 0.1d));
                double d35 = (double) f7;
                double d36 = (double) i6;
                Double.isNaN(d36);
                Double.isNaN(d35);
                this.Digital_time_Colon_Y_offset = (float) (d35 + (d36 * 0.06d));
                String str4 = this.mCalendar.get(9) == 0 ? "AM" : "PM";
                canvas.drawText(this.used12hours, this.Digital_time_Hours_X_offset, this.Digital_time_Hours_Y_offset, this.mPaintDigital_time_Hour);
                canvas.drawText(str4, this.Digital_time_Colon_X_offset, this.Digital_time_Colon_Y_offset, this.mPaintDigital_time_Colon);
                canvas.drawText(this.usedtwntymintues, this.Digital_time_Mintues_X_offset, this.Digital_time_Mintues_Y_offset, this.mPaintDigital_time_Min);
                Calendar_data();
                Paint paint9 = this.mPaint_date;
                double d37 = (double) this.radius;
                Double.isNaN(d37);
                paint9.setTextSize((float) (d37 * 0.05d));
                Paint paint10 = this.mPaint_date1;
                double d38 = (double) this.radius;
                Double.isNaN(d38);
                paint10.setTextSize((float) (d38 * 0.07d));
                Paint paint11 = this.mPaint_date2;
                double d39 = (double) this.radius;
                Double.isNaN(d39);
                paint11.setTextSize((float) (d39 * 0.05d));
                String str5 = this.usedweekday;
                double d40 = (double) this.Digital_time_Mintues_X_offset;
                int i7 = this.radius;
                double d41 = (double) i7;
                Double.isNaN(d41);
                Double.isNaN(d40);
                double d42 = (double) this.f205y;
                double d43 = (double) i7;
                Double.isNaN(d43);
                Double.isNaN(d42);
                canvas.drawText(str5, (float) (d40 - (d41 * 0.07d)), (float) (d42 + (d43 * 0.13d)), this.mPaint_date);
                String str6 = this.useddate;
                double d44 = (double) this.Digital_time_Mintues_X_offset;
                int i8 = this.radius;
                double d45 = (double) i8;
                Double.isNaN(d45);
                Double.isNaN(d44);
                double d46 = (double) this.f205y;
                double d47 = (double) i8;
                Double.isNaN(d47);
                Double.isNaN(d46);
                canvas.drawText(str6, (float) (d44 + (d45 * 0.05d)), (float) (d46 + (d47 * 0.13d)), this.mPaint_date1);
                BatteryManager batteryManager = (BatteryManager) this.context.getSystemService("batterymanager");
                if (Build.VERSION.SDK_INT >= 21) {
                    float f8 = this.f204x;
                    double d48 = (double) this.f205y;
                    double d49 = (double) this.radius;
                    Double.isNaN(d49);
                    Double.isNaN(d48);
                    canvas.drawText(batteryManager.getIntProperty(4) + "%", f8, (float) (d48 + (d49 * 0.25d)), this.mPaint_date2);
                    return;
                }
                return;
            case 2:
                Paint paint12 = this.mPaintDigital_time_Hour;
                double d50 = (double) this.radius;
                Double.isNaN(d50);
                paint12.setTextSize((float) (d50 * 0.27d));
                Paint paint13 = this.mPaintDigital_time_Min;
                double d51 = (double) this.radius;
                Double.isNaN(d51);
                paint13.setTextSize((float) (d51 * 0.27d));
                Paint paint14 = this.mPaintDigital_time_Colon;
                double d52 = (double) this.radius;
                Double.isNaN(d52);
                paint14.setTextSize((float) (d52 * 0.07d));
                float f9 = this.f204x;
                this.Digital_time_Hours_X_offset = f9;
                float f10 = this.f205y;
                double d53 = (double) f10;
                int i9 = this.radius;
                double d54 = (double) i9;
                Double.isNaN(d54);
                Double.isNaN(d53);
                float f11 = (float) (d53 - (d54 * 0.11d));
                this.Digital_time_Hours_Y_offset = f11;
                this.Digital_time_Mintues_X_offset = f9;
                double d55 = (double) f10;
                double d56 = (double) i9;
                Double.isNaN(d56);
                Double.isNaN(d55);
                this.Digital_time_Mintues_Y_offset = (float) (d55 + (d56 * 0.13d));
                double d57 = (double) f9;
                double d58 = (double) i9;
                Double.isNaN(d58);
                Double.isNaN(d57);
                this.Digital_time_Colon_X_offset = (float) (d57 + (d58 * 0.2d));
                double d59 = (double) f10;
                double d60 = (double) i9;
                Double.isNaN(d60);
                Double.isNaN(d59);
                this.Digital_time_Colon_Y_offset = (float) (d59 + (d60 * 0.05d));
                canvas.drawText(this.used12hours, f9, f11, this.mPaintDigital_time_Hour);
                canvas.drawText(this.usedtwntymintues, this.Digital_time_Mintues_X_offset, this.Digital_time_Mintues_Y_offset, this.mPaintDigital_time_Min);
                Calendar_data();
                Paint paint15 = this.mPaint_date;
                double d61 = (double) this.radius;
                Double.isNaN(d61);
                paint15.setTextSize((float) (d61 * 0.07d));
                Paint paint16 = this.mPaint_date1;
                double d62 = (double) this.radius;
                Double.isNaN(d62);
                paint16.setTextSize((float) (d62 * 0.07d));
                Paint paint17 = this.mPaint_date2;
                double d63 = (double) this.radius;
                Double.isNaN(d63);
                paint17.setTextSize((float) (d63 * 0.07d));
                String str7 = this.usedweekday;
                double d64 = (double) this.f204x;
                int i10 = this.radius;
                double d65 = (double) i10;
                Double.isNaN(d65);
                Double.isNaN(d64);
                double d66 = (double) this.f205y;
                double d67 = (double) i10;
                Double.isNaN(d67);
                Double.isNaN(d66);
                canvas.drawText(str7, (float) (d64 - (d65 * 0.11d)), (float) (d66 + (d67 * 0.23d)), this.mPaint_date);
                String str8 = this.useddate;
                double d68 = (double) this.f204x;
                int i11 = this.radius;
                double d69 = (double) i11;
                Double.isNaN(d69);
                Double.isNaN(d68);
                double d70 = (double) this.f205y;
                double d71 = (double) i11;
                Double.isNaN(d71);
                Double.isNaN(d70);
                canvas.drawText(str8, (float) (d68 - (d69 * 0.0d)), (float) (d70 + (d71 * 0.23d)), this.mPaint_date1);
                String str9 = this.usedmonth;
                double d72 = (double) this.f204x;
                int i12 = this.radius;
                double d73 = (double) i12;
                Double.isNaN(d73);
                Double.isNaN(d72);
                double d74 = (double) this.f205y;
                double d75 = (double) i12;
                Double.isNaN(d75);
                Double.isNaN(d74);
                canvas.drawText(str9, (float) (d72 + (d73 * 0.1d)), (float) (d74 + (d75 * 0.23d)), this.mPaint_date2);
                return;
            case 3:
                Paint paint18 = this.mPaintDigital_time_Min;
                double d76 = (double) this.radius;
                Double.isNaN(d76);
                paint18.setTextSize((float) (d76 * 0.23d));
                Paint paint19 = this.mPaintDigital_time_Hour;
                double d77 = (double) this.radius;
                Double.isNaN(d77);
                paint19.setTextSize((float) (d77 * 0.38d));
                Paint paint20 = this.mPaintDigital_time_Colon;
                double d78 = (double) this.radius;
                Double.isNaN(d78);
                paint20.setTextSize((float) (d78 * 0.07d));
                float f12 = this.f204x;
                double d79 = (double) f12;
                int i13 = this.radius;
                double d80 = (double) i13;
                Double.isNaN(d80);
                Double.isNaN(d79);
                float f13 = (float) (d79 - (d80 * 0.01d));
                this.Digital_time_Hours_X_offset = f13;
                float f14 = this.f205y;
                double d81 = (double) f14;
                double d82 = (double) i13;
                Double.isNaN(d82);
                Double.isNaN(d81);
                float f15 = (float) (d81 + (d82 * 0.05d));
                this.Digital_time_Hours_Y_offset = f15;
                double d83 = (double) f12;
                double d84 = (double) i13;
                Double.isNaN(d84);
                Double.isNaN(d83);
                float f16 = (float) (d83 + (d84 * 0.27d));
                this.Digital_time_Mintues_X_offset = f16;
                double d85 = (double) f14;
                double d86 = (double) i13;
                Double.isNaN(d86);
                Double.isNaN(d85);
                this.Digital_time_Mintues_Y_offset = (float) (d85 + (d86 * 0.19d));
                double d87 = (double) f16;
                double d88 = (double) i13;
                Double.isNaN(d88);
                Double.isNaN(d87);
                this.Digital_time_Colon_X_offset = (float) (d87 + (d88 * 0.2d));
                double d89 = (double) f14;
                double d90 = (double) i13;
                Double.isNaN(d90);
                Double.isNaN(d89);
                this.Digital_time_Colon_Y_offset = (float) (d89 + (d90 * 0.05d));
                canvas.drawText(this.used12hours, f13, f15, this.mPaintDigital_time_Hour);
                canvas.drawText(this.usedtwntymintues, this.Digital_time_Mintues_X_offset, this.Digital_time_Mintues_Y_offset, this.mPaintDigital_time_Min);
                Calendar_data();
                Paint paint21 = this.mPaint_date;
                double d91 = (double) this.radius;
                Double.isNaN(d91);
                paint21.setTextSize((float) (d91 * 0.12d));
                Paint paint22 = this.mPaint_date1;
                double d92 = (double) this.radius;
                Double.isNaN(d92);
                paint22.setTextSize((float) (d92 * 0.07d));
                Paint paint23 = this.mPaint_date2;
                double d93 = (double) this.radius;
                Double.isNaN(d93);
                paint23.setTextSize((float) (d93 * 0.07d));
                String str10 = this.usedweekday;
                double d94 = (double) this.f204x;
                int i14 = this.radius;
                double d95 = (double) i14;
                Double.isNaN(d95);
                Double.isNaN(d94);
                double d96 = (double) this.f205y;
                double d97 = (double) i14;
                Double.isNaN(d97);
                Double.isNaN(d96);
                canvas.drawText(str10, (float) (d94 + (d95 * 0.06d)), (float) (d96 + (d97 * 0.18d)), this.mPaint_date);
                return;
            case 4:
                Paint paint24 = this.mPaintDigital_time_Min;
                double d98 = (double) this.radius;
                Double.isNaN(d98);
                paint24.setTextSize((float) (d98 * 0.15d));
                Paint paint25 = this.mPaintDigital_time_Hour;
                double d99 = (double) this.radius;
                Double.isNaN(d99);
                paint25.setTextSize((float) (d99 * 0.15d));
                float f17 = this.f204x;
                double d100 = (double) f17;
                int i15 = this.radius;
                double d101 = (double) i15;
                Double.isNaN(d101);
                Double.isNaN(d100);
                float f18 = (float) (d100 - (d101 * 0.14d));
                this.Digital_time_Hours_X_offset = f18;
                float f19 = this.f205y;
                double d102 = (double) f19;
                double d103 = (double) i15;
                Double.isNaN(d103);
                Double.isNaN(d102);
                float f20 = (float) (d102 - (d103 * 0.05d));
                this.Digital_time_Hours_Y_offset = f20;
                this.Digital_time_Colon_X_offset = f17;
                double d104 = (double) f19;
                double d105 = (double) i15;
                Double.isNaN(d105);
                Double.isNaN(d104);
                this.Digital_time_Colon_Y_offset = (float) (d104 - (d105 * 0.06d));
                double d106 = (double) f17;
                double d107 = (double) i15;
                Double.isNaN(d107);
                Double.isNaN(d106);
                this.Digital_time_Mintues_X_offset = (float) (d106 + (d107 * 0.14d));
                double d108 = (double) f19;
                double d109 = (double) i15;
                Double.isNaN(d109);
                Double.isNaN(d108);
                this.Digital_time_Mintues_Y_offset = (float) (d108 - (d109 * 0.05d));
                canvas.drawText(this.used12hours, f18, f20, this.mPaintDigital_time_Hour);
                canvas.drawText(":", this.Digital_time_Colon_X_offset, this.Digital_time_Colon_Y_offset, this.mPaintDigital_time_Min);
                canvas.drawText(this.usedtwntymintues, this.Digital_time_Mintues_X_offset, this.Digital_time_Mintues_Y_offset, this.mPaintDigital_time_Min);
                Calendar_data();
                float f21 = this.f204x;
                double d110 = (double) f21;
                int i16 = this.radius;
                double d111 = (double) i16;
                Double.isNaN(d111);
                Double.isNaN(d110);
                float f22 = this.f205y;
                double d112 = (double) f21;
                double d113 = (double) i16;
                Double.isNaN(d113);
                Double.isNaN(d112);
                canvas.drawLine((float) (d110 - (d111 * 0.4d)), f22, (float) (d112 + (d113 * 0.4d)), f22, this.mPaintDigital_time_Colon);
                Paint paint26 = this.mPaint_date;
                double d114 = (double) this.radius;
                Double.isNaN(d114);
                paint26.setTextSize((float) (d114 * 0.07d));
                Paint paint27 = this.mPaint_date1;
                double d115 = (double) this.radius;
                Double.isNaN(d115);
                paint27.setTextSize((float) (d115 * 0.07d));
                Paint paint28 = this.mPaint_date2;
                double d116 = (double) this.radius;
                Double.isNaN(d116);
                paint28.setTextSize((float) (d116 * 0.06d));
                String str11 = this.usedweekday;
                double d117 = (double) this.f204x;
                int i17 = this.radius;
                double d118 = (double) i17;
                Double.isNaN(d118);
                Double.isNaN(d117);
                double d119 = (double) this.f205y;
                double d120 = (double) i17;
                Double.isNaN(d120);
                Double.isNaN(d119);
                canvas.drawText(str11, (float) (d117 - (d118 * 0.06d)), (float) (d119 + (d120 * 0.09d)), this.mPaint_date);
                String str12 = this.useddate;
                double d121 = (double) this.f204x;
                int i18 = this.radius;
                double d122 = (double) i18;
                Double.isNaN(d122);
                Double.isNaN(d121);
                double d123 = (double) this.f205y;
                double d124 = (double) i18;
                Double.isNaN(d124);
                Double.isNaN(d123);
                canvas.drawText(str12, (float) (d121 + (d122 * 0.08d)), (float) (d123 + (d124 * 0.09d)), this.mPaint_date1);
                String str13 = this.usedmonth;
                float f23 = this.f204x;
                double d125 = (double) this.f205y;
                double d126 = (double) this.radius;
                Double.isNaN(d126);
                Double.isNaN(d125);
                canvas.drawText(str13, f23, (float) (d125 + (d126 * 0.17d)), this.mPaint_date2);
                BatteryManager batteryManager2 = (BatteryManager) this.context.getSystemService("batterymanager");
                if (Build.VERSION.SDK_INT >= 21) {
                    int intProperty = batteryManager2.getIntProperty(4);
                    this.mPaint_date2.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "DIN Condensed Bold.ttf"));
                    float f24 = this.f204x;
                    double d127 = (double) this.f205y;
                    double d128 = (double) this.radius;
                    Double.isNaN(d128);
                    Double.isNaN(d127);
                    canvas.drawText(intProperty + "%", f24, (float) (d127 + (d128 * 0.25d)), this.mPaint_date2);
                    return;
                }
                return;
            case 5:
                Paint paint29 = this.mPaintDigital_time_Hour;
                double d129 = (double) this.radius;
                Double.isNaN(d129);
                paint29.setTextSize((float) (d129 * 0.27d));
                Paint paint30 = this.mPaintDigital_time_Min;
                double d130 = (double) this.radius;
                Double.isNaN(d130);
                paint30.setTextSize((float) (d130 * 0.17d));
                Paint paint31 = this.mPaintDigital_time_Colon;
                double d131 = (double) this.radius;
                Double.isNaN(d131);
                paint31.setTextSize((float) (d131 * 0.07d));
                float f25 = this.f204x;
                this.Digital_time_Hours_X_offset = f25;
                float f26 = this.f205y;
                this.Digital_time_Hours_Y_offset = f26;
                double d132 = (double) f25;
                int i19 = this.radius;
                double d133 = (double) i19;
                Double.isNaN(d133);
                Double.isNaN(d132);
                float f27 = (float) (d132 + (d133 * 0.08d));
                this.Digital_time_Mintues_X_offset = f27;
                double d134 = (double) f26;
                double d135 = (double) i19;
                Double.isNaN(d135);
                Double.isNaN(d134);
                this.Digital_time_Mintues_Y_offset = (float) (d134 + (d135 * 0.18d));
                double d136 = (double) f27;
                double d137 = (double) i19;
                Double.isNaN(d137);
                Double.isNaN(d136);
                this.Digital_time_Colon_X_offset = (float) (d136 + (d137 * 0.2d));
                double d138 = (double) f26;
                double d139 = (double) i19;
                Double.isNaN(d139);
                Double.isNaN(d138);
                this.Digital_time_Colon_Y_offset = (float) (d138 + (d139 * 0.2d));
                canvas.drawText(this.used12hours, f25, f26, this.mPaintDigital_time_Hour);
                canvas.drawText(this.usedtwntymintues, this.Digital_time_Mintues_X_offset, this.Digital_time_Mintues_Y_offset, this.mPaintDigital_time_Min);
                Calendar_data();
                Paint paint32 = this.mPaint_date;
                double d140 = (double) this.radius;
                Double.isNaN(d140);
                paint32.setTextSize((float) (d140 * 0.07d));
                Paint paint33 = this.mPaint_date1;
                double d141 = (double) this.radius;
                Double.isNaN(d141);
                paint33.setTextSize((float) (d141 * 0.07d));
                Paint paint34 = this.mPaint_date2;
                double d142 = (double) this.radius;
                Double.isNaN(d142);
                paint34.setTextSize((float) (d142 * 0.07d));
                String str14 = this.usedweekday;
                double d143 = (double) this.f204x;
                int i20 = this.radius;
                double d144 = (double) i20;
                Double.isNaN(d144);
                Double.isNaN(d143);
                double d145 = (double) this.f205y;
                double d146 = (double) i20;
                Double.isNaN(d146);
                Double.isNaN(d145);
                canvas.drawText(str14, (float) (d143 - (d144 * 0.13d)), (float) (d145 + (d146 * 0.08d)), this.mPaint_date);
                String str15 = this.useddate;
                double d147 = (double) this.f204x;
                int i21 = this.radius;
                double d148 = (double) i21;
                Double.isNaN(d148);
                Double.isNaN(d147);
                double d149 = (double) this.f205y;
                double d150 = (double) i21;
                Double.isNaN(d150);
                Double.isNaN(d149);
                canvas.drawText(str15, (float) (d147 - (d148 * 0.13d)), (float) (d149 + (d150 * 0.17d)), this.mPaint_date1);
                return;
            case 6:
                Paint paint35 = this.mPaintDigital_time_Hour;
                double d151 = (double) this.radius;
                Double.isNaN(d151);
                paint35.setTextSize((float) (d151 * 0.32d));
                Paint paint36 = this.mPaintDigital_time_Min;
                double d152 = (double) this.radius;
                Double.isNaN(d152);
                paint36.setTextSize((float) (d152 * 0.17d));
                Paint paint37 = this.mPaintDigital_time_Colon;
                double d153 = (double) this.radius;
                Double.isNaN(d153);
                paint37.setTextSize((float) (d153 * 0.07d));
                float f28 = this.f204x;
                double d154 = (double) f28;
                int i22 = this.radius;
                double d155 = (double) i22;
                Double.isNaN(d155);
                Double.isNaN(d154);
                float f29 = (float) (d154 - (d155 * 0.1d));
                this.Digital_time_Hours_X_offset = f29;
                float f30 = this.f205y;
                this.Digital_time_Hours_Y_offset = f30;
                double d156 = (double) f28;
                double d157 = (double) i22;
                Double.isNaN(d157);
                Double.isNaN(d156);
                float f31 = (float) (d156 + (d157 * 0.08d));
                this.Digital_time_Mintues_X_offset = f31;
                double d158 = (double) f30;
                double d159 = (double) i22;
                Double.isNaN(d159);
                Double.isNaN(d158);
                this.Digital_time_Mintues_Y_offset = (float) (d158 + (d159 * 0.18d));
                double d160 = (double) f31;
                double d161 = (double) i22;
                Double.isNaN(d161);
                Double.isNaN(d160);
                this.Digital_time_Colon_X_offset = (float) (d160 + (d161 * 0.2d));
                double d162 = (double) f30;
                double d163 = (double) i22;
                Double.isNaN(d163);
                Double.isNaN(d162);
                this.Digital_time_Colon_Y_offset = (float) (d162 + (d163 * 0.2d));
                canvas.drawText(this.used12hours, f29, f30, this.mPaintDigital_time_Hour);
                canvas.drawText(this.usedtwntymintues, this.Digital_time_Mintues_X_offset, this.Digital_time_Mintues_Y_offset, this.mPaintDigital_time_Min);
                Calendar_data();
                Paint paint38 = this.mPaint_date;
                double d164 = (double) this.radius;
                Double.isNaN(d164);
                paint38.setTextSize((float) (d164 * 0.07d));
                Paint paint39 = this.mPaint_date1;
                double d165 = (double) this.radius;
                Double.isNaN(d165);
                paint39.setTextSize((float) (d165 * 0.07d));
                Paint paint40 = this.mPaint_date2;
                double d166 = (double) this.radius;
                Double.isNaN(d166);
                paint40.setTextSize((float) (d166 * 0.07d));
                String str16 = this.usedweekday;
                double d167 = (double) this.f204x;
                int i23 = this.radius;
                double d168 = (double) i23;
                Double.isNaN(d168);
                Double.isNaN(d167);
                double d169 = (double) this.f205y;
                double d170 = (double) i23;
                Double.isNaN(d170);
                Double.isNaN(d169);
                canvas.drawText(str16, (float) (d167 - (d168 * 0.13d)), (float) (d169 + (d170 * 0.08d)), this.mPaint_date);
                String str17 = this.useddate;
                double d171 = (double) this.f204x;
                int i24 = this.radius;
                double d172 = (double) i24;
                Double.isNaN(d172);
                Double.isNaN(d171);
                double d173 = (double) this.f205y;
                double d174 = (double) i24;
                Double.isNaN(d174);
                Double.isNaN(d173);
                canvas.drawText(str17, (float) (d171 - (d172 * 0.13d)), (float) (d173 + (d174 * 0.17d)), this.mPaint_date1);
                BatteryManager batteryManager3 = (BatteryManager) this.context.getSystemService("batterymanager");
                if (Build.VERSION.SDK_INT >= 21) {
                    int intProperty2 = batteryManager3.getIntProperty(4);
                    this.mPaint_date2.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "DIN Condensed Bold.ttf"));
                    double d175 = (double) this.f204x;
                    int i25 = this.radius;
                    double d176 = (double) i25;
                    Double.isNaN(d176);
                    Double.isNaN(d175);
                    double d177 = (double) this.f205y;
                    double d178 = (double) i25;
                    Double.isNaN(d178);
                    Double.isNaN(d177);
                    canvas.drawText(intProperty2 + "%", (float) (d175 + (d176 * 0.13d)), (float) (d177 - (d178 * 0.0d)), this.mPaint_date2);
                    return;
                }
                return;
            case 7:
                Paint paint41 = this.mPaintDigital_time_Min;
                double d179 = (double) this.radius;
                Double.isNaN(d179);
                paint41.setTextSize((float) (d179 * 0.24d));
                Paint paint42 = this.mPaintDigital_time_Hour;
                double d180 = (double) this.radius;
                Double.isNaN(d180);
                paint42.setTextSize((float) (d180 * 0.38d));
                Paint paint43 = this.mPaintDigital_time_Colon;
                double d181 = (double) this.radius;
                Double.isNaN(d181);
                paint43.setTextSize((float) (d181 * 0.07d));
                float f32 = this.f204x;
                double d182 = (double) f32;
                int i26 = this.radius;
                double d183 = (double) i26;
                Double.isNaN(d183);
                Double.isNaN(d182);
                float f33 = (float) (d182 - (d183 * 0.01d));
                this.Digital_time_Hours_X_offset = f33;
                float f34 = this.f205y;
                double d184 = (double) f34;
                double d185 = (double) i26;
                Double.isNaN(d185);
                Double.isNaN(d184);
                float f35 = (float) (d184 + (d185 * 0.05d));
                this.Digital_time_Hours_Y_offset = f35;
                double d186 = (double) f32;
                double d187 = (double) i26;
                Double.isNaN(d187);
                Double.isNaN(d186);
                float f36 = (float) (d186 + (d187 * 0.27d));
                this.Digital_time_Mintues_X_offset = f36;
                double d188 = (double) f34;
                double d189 = (double) i26;
                Double.isNaN(d189);
                Double.isNaN(d188);
                this.Digital_time_Mintues_Y_offset = (float) (d188 + (d189 * 0.19d));
                double d190 = (double) f36;
                double d191 = (double) i26;
                Double.isNaN(d191);
                Double.isNaN(d190);
                this.Digital_time_Colon_X_offset = (float) (d190 + (d191 * 0.2d));
                double d192 = (double) f34;
                double d193 = (double) i26;
                Double.isNaN(d193);
                Double.isNaN(d192);
                this.Digital_time_Colon_Y_offset = (float) (d192 + (d193 * 0.05d));
                canvas.drawText(this.used12hours, f33, f35, this.mPaintDigital_time_Hour);
                canvas.drawText(this.usedtwntymintues, this.Digital_time_Mintues_X_offset, this.Digital_time_Mintues_Y_offset, this.mPaintDigital_time_Min);
                Calendar_data();
                Paint paint44 = this.mPaint_date;
                double d194 = (double) this.radius;
                Double.isNaN(d194);
                paint44.setTextSize((float) (d194 * 0.12d));
                Paint paint45 = this.mPaint_date1;
                double d195 = (double) this.radius;
                Double.isNaN(d195);
                paint45.setTextSize((float) (d195 * 0.07d));
                Paint paint46 = this.mPaint_date2;
                double d196 = (double) this.radius;
                Double.isNaN(d196);
                paint46.setTextSize((float) (d196 * 0.07d));
                String str18 = this.usedweekday;
                double d197 = (double) this.f204x;
                int i27 = this.radius;
                double d198 = (double) i27;
                Double.isNaN(d198);
                Double.isNaN(d197);
                double d199 = (double) this.f205y;
                double d200 = (double) i27;
                Double.isNaN(d200);
                Double.isNaN(d199);
                canvas.drawText(str18, (float) (d197 + (d198 * 0.06d)), (float) (d199 + (d200 * 0.18d)), this.mPaint_date);
                return;
            case 8:
                Paint paint47 = this.mPaintDigital_time_Min;
                double d201 = (double) this.radius;
                Double.isNaN(d201);
                paint47.setTextSize((float) (d201 * 0.24d));
                Paint paint48 = this.mPaintDigital_time_Hour;
                double d202 = (double) this.radius;
                Double.isNaN(d202);
                paint48.setTextSize((float) (d202 * 0.35d));
                Paint paint49 = this.mPaintDigital_time_Colon;
                double d203 = (double) this.radius;
                Double.isNaN(d203);
                paint49.setTextSize((float) (d203 * 0.07d));
                float f37 = this.f204x;
                double d204 = (double) f37;
                int i28 = this.radius;
                double d205 = (double) i28;
                Double.isNaN(d205);
                Double.isNaN(d204);
                float f38 = (float) (d204 - (d205 * 0.25d));
                this.Digital_time_Hours_X_offset = f38;
                float f39 = this.f205y;
                double d206 = (double) f39;
                double d207 = (double) i28;
                Double.isNaN(d207);
                Double.isNaN(d206);
                float f40 = (float) (d206 + (d207 * 0.08d));
                this.Digital_time_Hours_Y_offset = f40;
                double d208 = (double) f37;
                double d209 = (double) i28;
                Double.isNaN(d209);
                Double.isNaN(d208);
                float f41 = (float) (d208 - (d209 * 0.0d));
                this.Digital_time_Mintues_X_offset = f41;
                double d210 = (double) f39;
                double d211 = (double) i28;
                Double.isNaN(d211);
                Double.isNaN(d210);
                this.Digital_time_Mintues_Y_offset = (float) (d210 + (d211 * 0.19d));
                double d212 = (double) f41;
                double d213 = (double) i28;
                Double.isNaN(d213);
                Double.isNaN(d212);
                this.Digital_time_Colon_X_offset = (float) (d212 + (d213 * 0.2d));
                double d214 = (double) f39;
                double d215 = (double) i28;
                Double.isNaN(d215);
                Double.isNaN(d214);
                this.Digital_time_Colon_Y_offset = (float) (d214 + (d215 * 0.05d));
                canvas.drawText(this.used12hours, f38, f40, this.mPaintDigital_time_Hour);
                canvas.drawText(this.usedtwntymintues, this.Digital_time_Mintues_X_offset, this.Digital_time_Mintues_Y_offset, this.mPaintDigital_time_Min);
                Calendar_data();
                Paint paint50 = this.mPaint_date;
                double d216 = (double) this.radius;
                Double.isNaN(d216);
                paint50.setTextSize((float) (d216 * 0.12d));
                Paint paint51 = this.mPaint_date1;
                double d217 = (double) this.radius;
                Double.isNaN(d217);
                paint51.setTextSize((float) (d217 * 0.07d));
                Paint paint52 = this.mPaint_date2;
                double d218 = (double) this.radius;
                Double.isNaN(d218);
                paint52.setTextSize((float) (d218 * 0.07d));
                String str19 = this.usedweekday;
                double d219 = (double) this.f204x;
                int i29 = this.radius;
                double d220 = (double) i29;
                Double.isNaN(d220);
                Double.isNaN(d219);
                double d221 = (double) this.f205y;
                double d222 = (double) i29;
                Double.isNaN(d222);
                Double.isNaN(d221);
                canvas.drawText(str19, (float) (d219 - (d220 * 0.06d)), (float) (d221 + (d222 * 0.35d)), this.mPaint_date);
                return;
            case 9:
                Paint paint53 = this.mPaintDigital_time_Hour;
                double d223 = (double) this.radius;
                Double.isNaN(d223);
                paint53.setTextSize((float) (d223 * 0.2d));
                Paint paint54 = this.mPaintDigital_time_Min;
                double d224 = (double) this.radius;
                Double.isNaN(d224);
                paint54.setTextSize((float) (d224 * 0.2d));
                Paint paint55 = this.mPaintDigital_time_Colon;
                double d225 = (double) this.radius;
                Double.isNaN(d225);
                paint55.setTextSize((float) (d225 * 0.07d));
                float f42 = this.f204x;
                double d226 = (double) f42;
                int i30 = this.radius;
                double d227 = (double) i30;
                Double.isNaN(d227);
                Double.isNaN(d226);
                float f43 = (float) (d226 + (d227 * 0.15d));
                this.Digital_time_Hours_X_offset = f43;
                float f44 = this.f205y;
                double d228 = (double) f44;
                double d229 = (double) i30;
                Double.isNaN(d229);
                Double.isNaN(d228);
                float f45 = (float) (d228 - (d229 * 0.24d));
                this.Digital_time_Hours_Y_offset = f45;
                double d230 = (double) f42;
                double d231 = (double) i30;
                Double.isNaN(d231);
                Double.isNaN(d230);
                float f46 = (float) (d230 + (d231 * 0.15d));
                this.Digital_time_Mintues_X_offset = f46;
                double d232 = (double) f44;
                double d233 = (double) i30;
                Double.isNaN(d233);
                Double.isNaN(d232);
                this.Digital_time_Mintues_Y_offset = (float) (d232 - (d233 * 0.03d));
                double d234 = (double) f46;
                double d235 = (double) i30;
                Double.isNaN(d235);
                Double.isNaN(d234);
                this.Digital_time_Colon_X_offset = (float) (d234 + (d235 * 0.2d));
                double d236 = (double) f44;
                double d237 = (double) i30;
                Double.isNaN(d237);
                Double.isNaN(d236);
                this.Digital_time_Colon_Y_offset = (float) (d236 + (d237 * 0.05d));
                canvas.drawText(this.used12hours, f43, f45, this.mPaintDigital_time_Hour);
                canvas.drawText(this.usedtwntymintues, this.Digital_time_Mintues_X_offset, this.Digital_time_Mintues_Y_offset, this.mPaintDigital_time_Min);
                Calendar_data();
                Paint paint56 = this.mPaint_date;
                double d238 = (double) this.radius;
                Double.isNaN(d238);
                paint56.setTextSize((float) (d238 * 0.1d));
                Paint paint57 = this.mPaint_date1;
                double d239 = (double) this.radius;
                Double.isNaN(d239);
                paint57.setTextSize((float) (d239 * 0.1d));
                Paint paint58 = this.mPaint_date2;
                double d240 = (double) this.radius;
                Double.isNaN(d240);
                paint58.setTextSize((float) (d240 * 0.1d));
                String str20 = this.usedweekday;
                double d241 = (double) this.f204x;
                int i31 = this.radius;
                double d242 = (double) i31;
                Double.isNaN(d242);
                Double.isNaN(d241);
                double d243 = (double) this.f205y;
                double d244 = (double) i31;
                Double.isNaN(d244);
                Double.isNaN(d243);
                canvas.drawText(str20, (float) (d241 + (d242 * 0.34d)), (float) (d243 - (d244 * 0.03d)), this.mPaint_date);
                String str21 = this.useddate;
                double d245 = (double) this.f204x;
                int i32 = this.radius;
                double d246 = (double) i32;
                Double.isNaN(d246);
                Double.isNaN(d245);
                double d247 = (double) this.f205y;
                double d248 = (double) i32;
                Double.isNaN(d248);
                Double.isNaN(d247);
                canvas.drawText(str21, (float) (d245 + (d246 * 0.34d)), (float) (d247 - (d248 * 0.14d)), this.mPaint_date1);
                return;
            case 10:
                Paint paint59 = this.mPaintDigital_time_Hour;
                double d249 = (double) this.radius;
                Double.isNaN(d249);
                paint59.setTextSize((float) (d249 * 0.15d));
                Paint paint60 = this.mPaintDigital_time_Min;
                double d250 = (double) this.radius;
                Double.isNaN(d250);
                paint60.setTextSize((float) (d250 * 0.15d));
                Paint paint61 = this.mPaintDigital_time_Colon;
                double d251 = (double) this.radius;
                Double.isNaN(d251);
                paint61.setTextSize((float) (d251 * 0.07d));
                float f47 = this.f204x;
                double d252 = (double) f47;
                int i33 = this.radius;
                double d253 = (double) i33;
                Double.isNaN(d253);
                Double.isNaN(d252);
                float f48 = (float) (d252 + (d253 * 0.2d));
                this.Digital_time_Hours_X_offset = f48;
                float f49 = this.f205y;
                double d254 = (double) f49;
                double d255 = (double) i33;
                Double.isNaN(d255);
                Double.isNaN(d254);
                float f50 = (float) (d254 - (d255 * 0.01d));
                this.Digital_time_Hours_Y_offset = f50;
                double d256 = (double) f47;
                double d257 = (double) i33;
                Double.isNaN(d257);
                Double.isNaN(d256);
                float f51 = (float) (d256 + (d257 * 0.2d));
                this.Digital_time_Mintues_X_offset = f51;
                double d258 = (double) f49;
                double d259 = (double) i33;
                Double.isNaN(d259);
                Double.isNaN(d258);
                this.Digital_time_Mintues_Y_offset = (float) (d258 + (d259 * 0.15d));
                double d260 = (double) f51;
                double d261 = (double) i33;
                Double.isNaN(d261);
                Double.isNaN(d260);
                this.Digital_time_Colon_X_offset = (float) (d260 + (d261 * 0.2d));
                double d262 = (double) f49;
                double d263 = (double) i33;
                Double.isNaN(d263);
                Double.isNaN(d262);
                this.Digital_time_Colon_Y_offset = (float) (d262 + (d263 * 0.05d));
                canvas.drawText(this.used12hours, f48, f50, this.mPaintDigital_time_Hour);
                canvas.drawText(this.usedtwntymintues, this.Digital_time_Mintues_X_offset, this.Digital_time_Mintues_Y_offset, this.mPaintDigital_time_Min);
                Calendar_data();
                Paint paint62 = this.mPaint_date;
                double d264 = (double) this.radius;
                Double.isNaN(d264);
                paint62.setTextSize((float) (d264 * 0.1d));
                Paint paint63 = this.mPaint_date1;
                double d265 = (double) this.radius;
                Double.isNaN(d265);
                paint63.setTextSize((float) (d265 * 0.1d));
                Paint paint64 = this.mPaint_date2;
                double d266 = (double) this.radius;
                Double.isNaN(d266);
                paint64.setTextSize((float) (d266 * 0.1d));
                return;
            default:
                return;
        }
    }

    private void Calendar_data() {
        Date time = Calendar.getInstance().getTime();
        Calendar instance = Calendar.getInstance();
        instance.setTime(time);
        String[] split = new SimpleDateFormat("yyyy-MMM-dd").format(time).split("-");
        this.useddate = split[2];
        this.usedmonth = split[1].toUpperCase();
        this.usedweekday = this.stringsDays[instance.get(7) - 1];
    }

    public void setTextFace() {
        switch (this.textClockPosition) {
            case 0:
                this.mPaintDigital_time_Min.setColor(Color.parseColor("#00F5FA"));
                this.mPaintDigital_time_Colon.setColor(Color.parseColor("#00F5FA"));
                Bitmap decodeResource = BitmapFactory.decodeResource(this.context.getResources(), R.drawable.base_4);
                this.background_round = decodeResource;
                int i = this.radius;
                this.scaledbackground_round = Bitmap.createScaledBitmap(decodeResource, i, i, true);
                this.mPaint_date.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "montserrat_semi_bold.ttf"));
                this.mPaint_date1.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "montserrat_light.ttf"));
                this.mPaint_date2.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "montserrat_light.ttf"));
                this.mPaintDigital_time_Hour.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "montserrat_semi_bold.ttf"));
                this.mPaintDigital_time_Min.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "montserrat_light.ttf"));
                this.mPaintDigital_time_Colon.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "montserrat_light.ttf"));
                return;
            case 1:
                this.mPaintDigital_time_Min.setColor(Color.parseColor("#F96FFF"));
                this.mPaintDigital_time_Colon.setColor(Color.parseColor("#F96FFF"));
                Bitmap decodeResource2 = BitmapFactory.decodeResource(this.context.getResources(), R.drawable.base_5);
                this.background_round = decodeResource2;
                int i2 = this.radius;
                this.scaledbackground_round = Bitmap.createScaledBitmap(decodeResource2, i2, i2, true);
                this.mPaint_date.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "montserrat_semi_bold.ttf"));
                this.mPaint_date1.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "montserrat_light.ttf"));
                this.mPaint_date2.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "montserrat_light.ttf"));
                this.mPaintDigital_time_Hour.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "rubik_variablefont_wght.ttf"));
                this.mPaintDigital_time_Min.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "rubik_variablefont_wght.ttf"));
                this.mPaintDigital_time_Colon.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "rubik_variablefont_wght.ttf"));
                return;
            case 2:
                this.mPaintDigital_time_Min.setColor(Color.parseColor("#FEFE5E"));
                this.mPaintDigital_time_Colon.setColor(Color.parseColor("#FEFE5E"));
                Bitmap decodeResource3 = BitmapFactory.decodeResource(this.context.getResources(), R.drawable.base_2);
                this.background_round = decodeResource3;
                int i3 = this.radius;
                this.scaledbackground_round = Bitmap.createScaledBitmap(decodeResource3, i3, i3, true);
                this.mPaint_date.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "italicfont.ttf"));
                this.mPaint_date1.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "italicfont.ttf"));
                this.mPaint_date2.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "italicfont.ttf"));
                this.mPaintDigital_time_Hour.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "italicfont.ttf"));
                this.mPaintDigital_time_Min.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "italicfont.ttf"));
                this.mPaintDigital_time_Colon.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "italicfont.ttf"));
                return;
            case 3:
                this.mPaintDigital_time_Min.setColor(Color.parseColor("#62CEFF"));
                this.mPaintDigital_time_Colon.setColor(Color.parseColor("#62CEFF"));
                Bitmap decodeResource4 = BitmapFactory.decodeResource(this.context.getResources(), R.drawable.base_7);
                this.background_round = decodeResource4;
                int i4 = this.radius;
                this.scaledbackground_round = Bitmap.createScaledBitmap(decodeResource4, i4, i4, true);
                this.mPaint_date.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "pathwaygothicone_regular.ttf"));
                this.mPaint_date1.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "montserrat_light.ttf"));
                this.mPaint_date2.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "montserrat_light.ttf"));
                this.mPaintDigital_time_Hour.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "oswald_variable_font_wght.ttf"));
                this.mPaintDigital_time_Min.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "oswald_variable_font_wght.ttf"));
                this.mPaintDigital_time_Colon.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "rubik_variablefont_wght.ttf"));
                return;
            case 4:
                this.mPaintDigital_time_Min.setColor(Color.parseColor("#62CEFF"));
                this.mPaintDigital_time_Colon.setColor(Color.parseColor("#62CEFF"));
                Bitmap decodeResource5 = BitmapFactory.decodeResource(this.context.getResources(), R.drawable.base_9);
                this.background_round = decodeResource5;
                int i5 = this.radius;
                this.scaledbackground_round = Bitmap.createScaledBitmap(decodeResource5, i5, i5, true);
                this.mPaint_date.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "rubik_variablefont_wght.ttf"));
                this.mPaint_date1.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "rubik_variablefont_wght.ttf"));
                this.mPaint_date2.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "rubik_variablefont_wght.ttf"));
                this.mPaintDigital_time_Hour.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "open_sans_regular.ttf"));
                this.mPaintDigital_time_Min.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "open_sans_regular.ttf"));
                this.mPaintDigital_time_Colon.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "open_sans_regular.ttf"));
                Paint paint = this.mPaintDigital_time_Colon;
                double d = (double) this.radius;
                Double.isNaN(d);
                paint.setStrokeWidth((float) (d * 0.02d));
                return;
            case 5:
                this.mPaintDigital_time_Min.setColor(Color.parseColor("#FAE9A2"));
                this.mPaintDigital_time_Colon.setColor(Color.parseColor("#FAE9A2"));
                Bitmap decodeResource6 = BitmapFactory.decodeResource(this.context.getResources(), R.drawable.base_10);
                this.background_round = decodeResource6;
                int i6 = this.radius;
                this.scaledbackground_round = Bitmap.createScaledBitmap(decodeResource6, i6, i6, true);
                this.mPaint_date.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "jetbrains_mono_medium.ttf"));
                this.mPaint_date1.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "jetbrains_mono_medium.ttf"));
                this.mPaint_date2.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "jetbrains_mono_medium.ttf"));
                this.mPaintDigital_time_Hour.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "DelaGothicOne-Regular.ttf"));
                this.mPaintDigital_time_Min.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "DelaGothicOne-Regular.ttf"));
                this.mPaintDigital_time_Colon.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "rubik_variablefont_wght.ttf"));
                return;
            case 6:
                this.mPaintDigital_time_Hour.setColor(Color.parseColor("#060D29"));
                this.mPaintDigital_time_Min.setColor(Color.parseColor("#FAE9A2"));
                this.mPaintDigital_time_Colon.setColor(Color.parseColor("#FAE9A2"));
                Bitmap decodeResource7 = BitmapFactory.decodeResource(this.context.getResources(), R.drawable.base_3);
                this.background_round = decodeResource7;
                int i7 = this.radius;
                this.scaledbackground_round = Bitmap.createScaledBitmap(decodeResource7, i7, i7, true);
                this.mPaint_date.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "jetbrains_mono_medium.ttf"));
                this.mPaint_date1.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "jetbrains_mono_medium.ttf"));
                this.mPaint_date2.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "jetbrains_mono_medium.ttf"));
                this.mPaintDigital_time_Hour.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "THECHAMP-Gradient.otf"));
                this.mPaintDigital_time_Min.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "THECHAMP-Gradient.otf"));
                this.mPaintDigital_time_Colon.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "THECHAMP-Gradient.otf"));
                return;
            case 7:
                this.mPaintDigital_time_Hour.setColor(Color.parseColor("#060D29"));
                this.mPaintDigital_time_Min.setColor(Color.parseColor("#FD75D9"));
                this.mPaintDigital_time_Colon.setColor(Color.parseColor("#FD75D9"));
                this.mPaint_date.setColor(Color.parseColor("#000000"));
                this.mPaint_date1.setColor(Color.parseColor("#000000"));
                this.mPaint_date2.setColor(Color.parseColor("#000000"));
                Bitmap decodeResource8 = BitmapFactory.decodeResource(this.context.getResources(), R.drawable.base_1);
                this.background_round = decodeResource8;
                int i8 = this.radius;
                this.scaledbackground_round = Bitmap.createScaledBitmap(decodeResource8, i8, i8, true);
                this.mPaint_date.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "italicfont.ttf"));
                this.mPaint_date1.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "italicfont.ttf"));
                this.mPaint_date2.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "italicfont.ttf"));
                this.mPaintDigital_time_Hour.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "italicfont.ttf"));
                this.mPaintDigital_time_Min.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "italicfont.ttf"));
                this.mPaintDigital_time_Colon.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "italicfont.ttf"));
                return;
            case 8:
                this.mPaintDigital_time_Hour.setColor(Color.parseColor("#010193"));
                this.mPaintDigital_time_Min.setColor(Color.parseColor("#FD75D9"));
                this.mPaintDigital_time_Colon.setColor(Color.parseColor("#FD75D9"));
                this.mPaint_date.setColor(Color.parseColor("#000000"));
                this.mPaint_date1.setColor(Color.parseColor("#000000"));
                this.mPaint_date2.setColor(Color.parseColor("#000000"));
                Bitmap decodeResource9 = BitmapFactory.decodeResource(this.context.getResources(), R.drawable.base_12);
                this.background_round = decodeResource9;
                int i9 = this.radius;
                this.scaledbackground_round = Bitmap.createScaledBitmap(decodeResource9, i9, i9, true);
                this.mPaint_date.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "italicfont.ttf"));
                this.mPaint_date1.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "italicfont.ttf"));
                this.mPaint_date2.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "italicfont.ttf"));
                this.mPaintDigital_time_Hour.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "italicfont.ttf"));
                this.mPaintDigital_time_Min.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "italicfont.ttf"));
                this.mPaintDigital_time_Colon.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "italicfont.ttf"));
                return;
            case 9:
                this.mPaintDigital_time_Hour.setColor(Color.parseColor("#31016F"));
                this.mPaintDigital_time_Min.setColor(Color.parseColor("#7E00E9"));
                this.mPaintDigital_time_Colon.setColor(Color.parseColor("#7E00E9"));
                this.mPaint_date.setColor(Color.parseColor("#E50163"));
                this.mPaint_date1.setColor(Color.parseColor("#FF017B"));
                this.mPaint_date2.setColor(Color.parseColor("#FF017B"));
                Bitmap decodeResource10 = BitmapFactory.decodeResource(this.context.getResources(), R.drawable.base_15);
                this.background_round = decodeResource10;
                int i10 = this.radius;
                this.scaledbackground_round = Bitmap.createScaledBitmap(decodeResource10, i10, i10, true);
                this.mPaint_date.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "bigshoulders_stencil_display_regular.ttf"));
                this.mPaint_date1.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "bigshoulders_stencil_display_regular.ttf"));
                this.mPaint_date2.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "bigshoulders_stencil_display_regular.ttf"));
                this.mPaintDigital_time_Hour.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "bigshoulders_stencil_display_regular.ttf"));
                this.mPaintDigital_time_Min.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "bigshoulders_stencil_display_regular.ttf"));
                this.mPaintDigital_time_Colon.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "bigshoulders_stencil_display_regular.ttf"));
                return;
            case 10:
                this.mPaintDigital_time_Hour.setColor(Color.parseColor("#262626"));
                this.mPaintDigital_time_Min.setColor(Color.parseColor("#262626"));
                this.mPaintDigital_time_Colon.setColor(Color.parseColor("#262626"));
                this.mPaint_date.setColor(Color.parseColor("#262626"));
                this.mPaint_date1.setColor(Color.parseColor("#262626"));
                this.mPaint_date2.setColor(Color.parseColor("#262626"));
                Bitmap decodeResource11 = BitmapFactory.decodeResource(this.context.getResources(), R.drawable.base_11);
                this.background_round = decodeResource11;
                int i11 = this.radius;
                this.scaledbackground_round = Bitmap.createScaledBitmap(decodeResource11, i11, i11, true);
                this.mPaint_date.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "oswald_variable_font_wght.ttf"));
                this.mPaint_date1.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "oswald_variable_font_wght.ttf"));
                this.mPaint_date2.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "oswald_variable_font_wght.ttf"));
                this.mPaintDigital_time_Hour.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "oswald_variable_font_wght.ttf"));
                this.mPaintDigital_time_Min.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "oswald_variable_font_wght.ttf"));
                this.mPaintDigital_time_Colon.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "oswald_variable_font_wght.ttf"));
                return;
            default:
                return;
        }
    }
}
