package com.clock.livewallpaper.viewUtils;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.Paint;
import android.graphics.Typeface;
import android.text.TextPaint;
import android.util.AttributeSet;
import android.view.View;
import androidx.core.view.InputDeviceCompat;
import com.clock.livewallpaper.utils.TinyDB;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;



public class TextClockPreview extends View {
    float Digital_time_Colon_X_offset;
    float Digital_time_Colon_Y_offset;
    float Digital_time_Hours_X_offset;
    float Digital_time_Hours_Y_offset;
    float Digital_time_Mintues_X_offset;
    float Digital_time_Mintues_Y_offset;
    Context context;
    private Calendar mCalendar;
    private Paint mPaintDigital_time_Colon;
    private Paint mPaintDigital_time_Hour;
    private Paint mPaintDigital_time_Min;
    private Paint mPaint_date;
    private Paint mPaint_date1;
    private Paint mPaint_date2;
    private Paint scaledmFilterPaint;
    private int t12hours;
    TinyDB tinyDB;
    private int twntmintues;
    private String used12hours;
    private String usedtwntymintues;
    private int sizeScaled = -1;
    private String useddate = "";
    private String usedmonth = "MM";
    private String usedweekday = "DD";
    private int textClockPosition = 9;


    private float f206x = 250.0f;


    private float f207y = 100.0f;
    private int radius = 880;
    private String[] stringsDays = {"SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"};
    private int color1 = -1;
    private int color2 = InputDeviceCompat.SOURCE_ANY;

    public TextClockPreview(Context context) {
        super(context);
        this.tinyDB = new TinyDB(context);
        this.context = context;
        init();
        config(this.f206x, this.f207y, this.radius);
    }

    public TextClockPreview(Context context, AttributeSet attributeSet) {
        super(context, attributeSet);
        this.tinyDB = new TinyDB(context);
        this.context = context;
        init();
        config(this.f206x, this.f207y, this.radius);
    }

    public void config(float f, float f2, int i) {
        this.f206x = f;
        this.f207y = f2;
        this.radius = i / 2;
        invalidate();
    }

    @Override
    public void onDraw(Canvas canvas) {
        super.onDraw(canvas);
        drawBg(canvas);
    }

    public int getTextClockPosition() {
        return this.textClockPosition;
    }

    public void setTextClockPosition(int i) {
        this.textClockPosition = i;
        init();
        invalidate();
    }

    public void init() {
        Calendar instance = Calendar.getInstance();
        this.mCalendar = instance;
        instance.setTimeInMillis(System.currentTimeMillis());
        Paint paint = new Paint();
        this.scaledmFilterPaint = paint;
        paint.setFilterBitmap(true);
        TextPaint textPaint = new TextPaint();
        this.mPaint_date = textPaint;
        textPaint.setTextAlign(Paint.Align.CENTER);
        this.mPaint_date.setAntiAlias(true);
        TextPaint textPaint2 = new TextPaint();
        this.mPaint_date1 = textPaint2;
        textPaint2.setTextAlign(Paint.Align.CENTER);
        this.mPaint_date1.setAntiAlias(true);
        TextPaint textPaint3 = new TextPaint();
        this.mPaint_date2 = textPaint3;
        textPaint3.setTextAlign(Paint.Align.CENTER);
        this.mPaint_date2.setAntiAlias(true);
        TextPaint textPaint4 = new TextPaint();
        this.mPaintDigital_time_Hour = textPaint4;
        textPaint4.setTextAlign(Paint.Align.CENTER);
        this.mPaintDigital_time_Hour.setAntiAlias(true);
        TextPaint textPaint5 = new TextPaint();
        this.mPaintDigital_time_Min = textPaint5;
        textPaint5.setTextAlign(Paint.Align.CENTER);
        this.mPaintDigital_time_Min.setAntiAlias(true);
        TextPaint textPaint6 = new TextPaint();
        this.mPaintDigital_time_Colon = textPaint6;
        textPaint6.setTextAlign(Paint.Align.CENTER);
        this.mPaintDigital_time_Colon.setAntiAlias(true);
        this.mPaintDigital_time_Hour.setColor(this.color1);
        this.mPaintDigital_time_Min.setColor(this.color2);
        this.mPaintDigital_time_Colon.setColor(this.color2);
        this.mPaint_date.setColor(this.color1);
        this.mPaint_date1.setColor(this.color1);
        this.mPaint_date2.setColor(this.color1);
        setTextFace();
    }

    private void drawBg(Canvas canvas) {
        canvas.drawColor(0);
        Calendar instance = Calendar.getInstance();
        this.mCalendar = instance;
        this.t12hours = instance.get(10);
        this.used12hours = this.t12hours + "";
        this.twntmintues = this.mCalendar.get(12);
        this.usedtwntymintues = this.twntmintues + "";
        int i = this.t12hours;
        if (i == 0) {
            this.used12hours = "12";
        }
        if (i < 10) {
            this.used12hours = "0" + this.t12hours;
        }
        if (this.twntmintues < 10) {
            this.usedtwntymintues = "0" + this.twntmintues;
        }
        if (this.twntmintues < 10) {
            this.usedtwntymintues = "0" + this.twntmintues;
        }
        if (this.t12hours == 0) {
            this.used12hours = "12";
        }
        switch (this.textClockPosition) {
            case 0:
                Paint paint = this.mPaintDigital_time_Min;
                double d = (double) this.radius;
                Double.isNaN(d);
                paint.setTextSize((float) (d * 0.4d));
                Paint paint2 = this.mPaintDigital_time_Hour;
                double d2 = (double) this.radius;
                Double.isNaN(d2);
                paint2.setTextSize((float) (d2 * 0.4d));
                float f = this.f206x;
                double d3 = (double) f;
                int i2 = this.radius;
                double d4 = (double) i2;
                Double.isNaN(d4);
                Double.isNaN(d3);
                float f2 = (float) (d3 - (d4 * 0.29d));
                this.Digital_time_Hours_X_offset = f2;
                float f3 = this.f207y;
                double d5 = (double) f3;
                double d6 = (double) i2;
                Double.isNaN(d6);
                Double.isNaN(d5);
                float f4 = (float) (d5 + (d6 * 0.13d));
                this.Digital_time_Hours_Y_offset = f4;
                this.Digital_time_Colon_X_offset = f;
                double d7 = (double) f3;
                double d8 = (double) i2;
                Double.isNaN(d8);
                Double.isNaN(d7);
                this.Digital_time_Colon_Y_offset = (float) (d7 + (d8 * 0.13d));
                double d9 = (double) f;
                double d10 = (double) i2;
                Double.isNaN(d10);
                Double.isNaN(d9);
                this.Digital_time_Mintues_X_offset = (float) (d9 + (d10 * 0.29d));
                double d11 = (double) f3;
                double d12 = (double) i2;
                Double.isNaN(d12);
                Double.isNaN(d11);
                this.Digital_time_Mintues_Y_offset = (float) (d11 + (d12 * 0.13d));
                canvas.drawText(this.used12hours, f2, f4, this.mPaintDigital_time_Hour);
                canvas.drawText(":", this.Digital_time_Colon_X_offset, this.Digital_time_Colon_Y_offset, this.mPaintDigital_time_Min);
                canvas.drawText(this.usedtwntymintues, this.Digital_time_Mintues_X_offset, this.Digital_time_Mintues_Y_offset, this.mPaintDigital_time_Min);
                Calendar_data();
                Paint paint3 = this.mPaint_date;
                double d13 = (double) this.radius;
                Double.isNaN(d13);
                paint3.setTextSize((float) (d13 * 0.1d));
                Paint paint4 = this.mPaint_date1;
                double d14 = (double) this.radius;
                Double.isNaN(d14);
                paint4.setTextSize((float) (d14 * 0.1d));
                Paint paint5 = this.mPaint_date2;
                double d15 = (double) this.radius;
                Double.isNaN(d15);
                paint5.setTextSize((float) (d15 * 0.1d));
                String str = this.usedweekday;
                double d16 = (double) this.f206x;
                int i3 = this.radius;
                double d17 = (double) i3;
                Double.isNaN(d17);
                Double.isNaN(d16);
                double d18 = (double) this.f207y;
                double d19 = (double) i3;
                Double.isNaN(d19);
                Double.isNaN(d18);
                canvas.drawText(str, (float) (d16 - (d17 * 0.21d)), (float) (d18 + (d19 * 0.3d)), this.mPaint_date);
                String str2 = this.useddate;
                float f5 = this.f206x;
                double d20 = (double) this.f207y;
                double d21 = (double) this.radius;
                Double.isNaN(d21);
                Double.isNaN(d20);
                canvas.drawText(str2, f5, (float) (d20 + (d21 * 0.3d)), this.mPaint_date1);
                String str3 = this.usedmonth;
                double d22 = (double) this.f206x;
                int i4 = this.radius;
                double d23 = (double) i4;
                Double.isNaN(d23);
                Double.isNaN(d22);
                double d24 = (double) this.f207y;
                double d25 = (double) i4;
                Double.isNaN(d25);
                Double.isNaN(d24);
                canvas.drawText(str3, (float) (d22 + (d23 * 0.2d)), (float) (d24 + (d25 * 0.3d)), this.mPaint_date2);
                return;
            case 1:
                Paint paint6 = this.mPaintDigital_time_Min;
                double d26 = (double) this.radius;
                Double.isNaN(d26);
                paint6.setTextSize((float) (d26 * 0.25d));
                Paint paint7 = this.mPaintDigital_time_Hour;
                double d27 = (double) this.radius;
                Double.isNaN(d27);
                paint7.setTextSize((float) (d27 * 0.39d));
                Paint paint8 = this.mPaintDigital_time_Colon;
                double d28 = (double) this.radius;
                Double.isNaN(d28);
                paint8.setTextSize((float) (d28 * 0.07d));
                float f6 = this.f206x;
                double d29 = (double) f6;
                int i5 = this.radius;
                double d30 = (double) i5;
                Double.isNaN(d30);
                Double.isNaN(d29);
                this.Digital_time_Hours_X_offset = (float) (d29 - (d30 * 0.17d));
                float f7 = this.f207y;
                double d31 = (double) f7;
                double d32 = (double) i5;
                Double.isNaN(d32);
                Double.isNaN(d31);
                this.Digital_time_Hours_Y_offset = (float) (d31 + (d32 * 0.13d));
                double d33 = (double) f6;
                double d34 = (double) i5;
                Double.isNaN(d34);
                Double.isNaN(d33);
                float f8 = (float) (d33 + (d34 * 0.2d));
                this.Digital_time_Mintues_X_offset = f8;
                double d35 = (double) f7;
                double d36 = (double) i5;
                Double.isNaN(d36);
                Double.isNaN(d35);
                this.Digital_time_Mintues_Y_offset = (float) (d35 + (d36 * 0.05d));
                double d37 = (double) f8;
                double d38 = (double) i5;
                Double.isNaN(d38);
                Double.isNaN(d37);
                this.Digital_time_Colon_X_offset = (float) (d37 + (d38 * 0.2d));
                double d39 = (double) f7;
                double d40 = (double) i5;
                Double.isNaN(d40);
                Double.isNaN(d39);
                this.Digital_time_Colon_Y_offset = (float) (d39 + (d40 * 0.05d));
                String str4 = this.mCalendar.get(9) == 0 ? "AM" : "PM";
                canvas.drawText(this.used12hours, this.Digital_time_Hours_X_offset, this.Digital_time_Hours_Y_offset, this.mPaintDigital_time_Hour);
                canvas.drawText(str4, this.Digital_time_Colon_X_offset, this.Digital_time_Colon_Y_offset, this.mPaintDigital_time_Colon);
                canvas.drawText(this.usedtwntymintues, this.Digital_time_Mintues_X_offset, this.Digital_time_Mintues_Y_offset, this.mPaintDigital_time_Min);
                Calendar_data();
                Paint paint9 = this.mPaint_date;
                double d41 = (double) this.radius;
                Double.isNaN(d41);
                paint9.setTextSize((float) (d41 * 0.05d));
                Paint paint10 = this.mPaint_date1;
                double d42 = (double) this.radius;
                Double.isNaN(d42);
                paint10.setTextSize((float) (d42 * 0.07d));
                Paint paint11 = this.mPaint_date2;
                double d43 = (double) this.radius;
                Double.isNaN(d43);
                paint11.setTextSize((float) (d43 * 0.07d));
                String str5 = this.usedweekday;
                double d44 = (double) this.Digital_time_Mintues_X_offset;
                int i6 = this.radius;
                double d45 = (double) i6;
                Double.isNaN(d45);
                Double.isNaN(d44);
                double d46 = (double) this.f207y;
                double d47 = (double) i6;
                Double.isNaN(d47);
                Double.isNaN(d46);
                canvas.drawText(str5, (float) (d44 - (d45 * 0.07d)), (float) (d46 + (d47 * 0.13d)), this.mPaint_date);
                String str6 = this.useddate;
                double d48 = (double) this.Digital_time_Mintues_X_offset;
                int i7 = this.radius;
                double d49 = (double) i7;
                Double.isNaN(d49);
                Double.isNaN(d48);
                double d50 = (double) this.f207y;
                double d51 = (double) i7;
                Double.isNaN(d51);
                Double.isNaN(d50);
                canvas.drawText(str6, (float) (d48 + (d49 * 0.05d)), (float) (d50 + (d51 * 0.13d)), this.mPaint_date1);
                String str7 = this.usedmonth;
                double d52 = (double) this.Digital_time_Mintues_X_offset;
                int i8 = this.radius;
                double d53 = (double) i8;
                Double.isNaN(d53);
                Double.isNaN(d52);
                double d54 = (double) this.f207y;
                double d55 = (double) i8;
                Double.isNaN(d55);
                Double.isNaN(d54);
                canvas.drawText(str7, (float) (d52 + (d53 * 0.18d)), (float) (d54 + (d55 * 0.13d)), this.mPaint_date2);
                return;
            case 2:
                Paint paint12 = this.mPaintDigital_time_Hour;
                double d56 = (double) this.radius;
                Double.isNaN(d56);
                paint12.setTextSize((float) (d56 * 0.27d));
                Paint paint13 = this.mPaintDigital_time_Min;
                double d57 = (double) this.radius;
                Double.isNaN(d57);
                paint13.setTextSize((float) (d57 * 0.27d));
                Paint paint14 = this.mPaintDigital_time_Colon;
                double d58 = (double) this.radius;
                Double.isNaN(d58);
                paint14.setTextSize((float) (d58 * 0.07d));
                float f9 = this.f206x;
                this.Digital_time_Hours_X_offset = f9;
                float f10 = this.f207y;
                double d59 = (double) f10;
                int i9 = this.radius;
                double d60 = (double) i9;
                Double.isNaN(d60);
                Double.isNaN(d59);
                float f11 = (float) (d59 - (d60 * 0.13d));
                this.Digital_time_Hours_Y_offset = f11;
                this.Digital_time_Mintues_X_offset = f9;
                double d61 = (double) f10;
                double d62 = (double) i9;
                Double.isNaN(d62);
                Double.isNaN(d61);
                this.Digital_time_Mintues_Y_offset = (float) (d61 + (d62 * 0.13d));
                double d63 = (double) f9;
                double d64 = (double) i9;
                Double.isNaN(d64);
                Double.isNaN(d63);
                this.Digital_time_Colon_X_offset = (float) (d63 + (d64 * 0.2d));
                double d65 = (double) f10;
                double d66 = (double) i9;
                Double.isNaN(d66);
                Double.isNaN(d65);
                this.Digital_time_Colon_Y_offset = (float) (d65 + (d66 * 0.05d));
                canvas.drawText(this.used12hours, f9, f11, this.mPaintDigital_time_Hour);
                canvas.drawText(this.usedtwntymintues, this.Digital_time_Mintues_X_offset, this.Digital_time_Mintues_Y_offset, this.mPaintDigital_time_Min);
                Calendar_data();
                Paint paint15 = this.mPaint_date;
                double d67 = (double) this.radius;
                Double.isNaN(d67);
                paint15.setTextSize((float) (d67 * 0.07d));
                Paint paint16 = this.mPaint_date1;
                double d68 = (double) this.radius;
                Double.isNaN(d68);
                paint16.setTextSize((float) (d68 * 0.07d));
                Paint paint17 = this.mPaint_date2;
                double d69 = (double) this.radius;
                Double.isNaN(d69);
                paint17.setTextSize((float) (d69 * 0.07d));
                String str8 = this.usedweekday;
                double d70 = (double) this.f206x;
                int i10 = this.radius;
                double d71 = (double) i10;
                Double.isNaN(d71);
                Double.isNaN(d70);
                double d72 = (double) this.f207y;
                double d73 = (double) i10;
                Double.isNaN(d73);
                Double.isNaN(d72);
                canvas.drawText(str8, (float) (d70 - (d71 * 0.13d)), (float) (d72 + (d73 * 0.23d)), this.mPaint_date);
                String str9 = this.useddate;
                double d74 = (double) this.f206x;
                int i11 = this.radius;
                double d75 = (double) i11;
                Double.isNaN(d75);
                Double.isNaN(d74);
                double d76 = (double) this.f207y;
                double d77 = (double) i11;
                Double.isNaN(d77);
                Double.isNaN(d76);
                canvas.drawText(str9, (float) (d74 - (d75 * 0.0d)), (float) (d76 + (d77 * 0.23d)), this.mPaint_date1);
                String str10 = this.usedmonth;
                double d78 = (double) this.f206x;
                int i12 = this.radius;
                double d79 = (double) i12;
                Double.isNaN(d79);
                Double.isNaN(d78);
                double d80 = (double) this.f207y;
                double d81 = (double) i12;
                Double.isNaN(d81);
                Double.isNaN(d80);
                canvas.drawText(str10, (float) (d78 + (d79 * 0.13d)), (float) (d80 + (d81 * 0.23d)), this.mPaint_date2);
                return;
            case 3:
                Paint paint18 = this.mPaintDigital_time_Min;
                double d82 = (double) this.radius;
                Double.isNaN(d82);
                paint18.setTextSize((float) (d82 * 0.23d));
                Paint paint19 = this.mPaintDigital_time_Hour;
                double d83 = (double) this.radius;
                Double.isNaN(d83);
                paint19.setTextSize((float) (d83 * 0.38d));
                Paint paint20 = this.mPaintDigital_time_Colon;
                double d84 = (double) this.radius;
                Double.isNaN(d84);
                paint20.setTextSize((float) (d84 * 0.07d));
                float f12 = this.f206x;
                double d85 = (double) f12;
                int i13 = this.radius;
                double d86 = (double) i13;
                Double.isNaN(d86);
                Double.isNaN(d85);
                float f13 = (float) (d85 - (d86 * 0.17d));
                this.Digital_time_Hours_X_offset = f13;
                float f14 = this.f207y;
                double d87 = (double) f14;
                double d88 = (double) i13;
                Double.isNaN(d88);
                Double.isNaN(d87);
                float f15 = (float) (d87 + (d88 * 0.13d));
                this.Digital_time_Hours_Y_offset = f15;
                double d89 = (double) f12;
                double d90 = (double) i13;
                Double.isNaN(d90);
                Double.isNaN(d89);
                float f16 = (float) (d89 + (d90 * 0.13d));
                this.Digital_time_Mintues_X_offset = f16;
                double d91 = (double) f14;
                double d92 = (double) i13;
                Double.isNaN(d92);
                Double.isNaN(d91);
                this.Digital_time_Mintues_Y_offset = (float) (d91 + (d92 * 0.02d));
                double d93 = (double) f16;
                double d94 = (double) i13;
                Double.isNaN(d94);
                Double.isNaN(d93);
                this.Digital_time_Colon_X_offset = (float) (d93 + (d94 * 0.2d));
                double d95 = (double) f14;
                double d96 = (double) i13;
                Double.isNaN(d96);
                Double.isNaN(d95);
                this.Digital_time_Colon_Y_offset = (float) (d95 + (d96 * 0.05d));
                canvas.drawText(this.used12hours, f13, f15, this.mPaintDigital_time_Hour);
                canvas.drawText(this.usedtwntymintues, this.Digital_time_Mintues_X_offset, this.Digital_time_Mintues_Y_offset, this.mPaintDigital_time_Min);
                Calendar_data();
                Paint paint21 = this.mPaint_date;
                double d97 = (double) this.radius;
                Double.isNaN(d97);
                paint21.setTextSize((float) (d97 * 0.12d));
                Paint paint22 = this.mPaint_date1;
                double d98 = (double) this.radius;
                Double.isNaN(d98);
                paint22.setTextSize((float) (d98 * 0.07d));
                Paint paint23 = this.mPaint_date2;
                double d99 = (double) this.radius;
                Double.isNaN(d99);
                paint23.setTextSize((float) (d99 * 0.07d));
                String str11 = this.usedweekday;
                double d100 = (double) this.Digital_time_Mintues_X_offset;
                int i14 = this.radius;
                double d101 = (double) i14;
                Double.isNaN(d101);
                Double.isNaN(d100);
                double d102 = (double) this.f207y;
                double d103 = (double) i14;
                Double.isNaN(d103);
                Double.isNaN(d102);
                canvas.drawText(str11, (float) (d100 + (d101 * 0.0d)), (float) (d102 + (d103 * 0.14d)), this.mPaint_date);
                return;
            case 4:
                Paint paint24 = this.mPaintDigital_time_Min;
                double d104 = (double) this.radius;
                Double.isNaN(d104);
                paint24.setTextSize((float) (d104 * 0.25d));
                Paint paint25 = this.mPaintDigital_time_Hour;
                double d105 = (double) this.radius;
                Double.isNaN(d105);
                paint25.setTextSize((float) (d105 * 0.25d));
                float f17 = this.f206x;
                double d106 = (double) f17;
                int i15 = this.radius;
                double d107 = (double) i15;
                Double.isNaN(d107);
                Double.isNaN(d106);
                float f18 = (float) (d106 - (d107 * 0.36d));
                this.Digital_time_Hours_X_offset = f18;
                float f19 = this.f207y;
                double d108 = (double) f19;
                double d109 = (double) i15;
                Double.isNaN(d109);
                Double.isNaN(d108);
                float f20 = (float) (d108 + (d109 * 0.13d));
                this.Digital_time_Hours_Y_offset = f20;
                double d110 = (double) f17;
                double d111 = (double) i15;
                Double.isNaN(d111);
                Double.isNaN(d110);
                this.Digital_time_Colon_X_offset = (float) (d110 - (d111 * 0.18d));
                double d112 = (double) f19;
                double d113 = (double) i15;
                Double.isNaN(d113);
                Double.isNaN(d112);
                this.Digital_time_Colon_Y_offset = (float) (d112 + (d113 * 0.12d));
                this.Digital_time_Mintues_X_offset = f17;
                double d114 = (double) f19;
                double d115 = (double) i15;
                Double.isNaN(d115);
                Double.isNaN(d114);
                this.Digital_time_Mintues_Y_offset = (float) (d114 + (d115 * 0.13d));
                canvas.drawText(this.used12hours, f18, f20, this.mPaintDigital_time_Hour);
                canvas.drawText(":", this.Digital_time_Colon_X_offset, this.Digital_time_Colon_Y_offset, this.mPaintDigital_time_Min);
                canvas.drawText(this.usedtwntymintues, this.Digital_time_Mintues_X_offset, this.Digital_time_Mintues_Y_offset, this.mPaintDigital_time_Min);
                Calendar_data();
                float f21 = this.f206x;
                double d116 = (double) f21;
                int i16 = this.radius;
                double d117 = (double) i16;
                Double.isNaN(d117);
                Double.isNaN(d116);
                float f22 = this.f207y;
                double d118 = (double) f22;
                double d119 = (double) i16;
                Double.isNaN(d119);
                Double.isNaN(d118);
                double d120 = (double) f21;
                double d121 = (double) i16;
                Double.isNaN(d121);
                Double.isNaN(d120);
                float f23 = (float) (d120 + (d121 * 0.2d));
                double d122 = (double) f22;
                double d123 = (double) i16;
                Double.isNaN(d123);
                Double.isNaN(d122);
                canvas.drawLine((float) (d116 + (d117 * 0.2d)), (float) (d118 - (d119 * 0.13d)), f23, (float) (d122 + (d123 * 0.21d)), this.mPaintDigital_time_Colon);
                Paint paint26 = this.mPaint_date;
                double d124 = (double) this.radius;
                Double.isNaN(d124);
                paint26.setTextSize((float) (d124 * 0.1d));
                Paint paint27 = this.mPaint_date1;
                double d125 = (double) this.radius;
                Double.isNaN(d125);
                paint27.setTextSize((float) (d125 * 0.1d));
                Paint paint28 = this.mPaint_date2;
                double d126 = (double) this.radius;
                Double.isNaN(d126);
                paint28.setTextSize((float) (d126 * 0.1d));
                String str12 = this.usedweekday;
                double d127 = (double) this.f206x;
                int i17 = this.radius;
                double d128 = (double) i17;
                Double.isNaN(d128);
                Double.isNaN(d127);
                double d129 = (double) this.f207y;
                double d130 = (double) i17;
                Double.isNaN(d130);
                Double.isNaN(d129);
                canvas.drawText(str12, (float) (d127 + (d128 * 0.35d)), (float) (d129 - (d130 * 0.05d)), this.mPaint_date);
                String str13 = this.useddate;
                double d131 = (double) this.f206x;
                int i18 = this.radius;
                double d132 = (double) i18;
                Double.isNaN(d132);
                Double.isNaN(d131);
                double d133 = (double) this.f207y;
                double d134 = (double) i18;
                Double.isNaN(d134);
                Double.isNaN(d133);
                canvas.drawText(str13, (float) (d131 + (d132 * 0.35d)), (float) (d133 + (d134 * 0.08d)), this.mPaint_date1);
                String str14 = this.usedmonth;
                double d135 = (double) this.f206x;
                int i19 = this.radius;
                double d136 = (double) i19;
                Double.isNaN(d136);
                Double.isNaN(d135);
                double d137 = (double) this.f207y;
                double d138 = (double) i19;
                Double.isNaN(d138);
                Double.isNaN(d137);
                canvas.drawText(str14, (float) (d135 + (d136 * 0.35d)), (float) (d137 + (d138 * 0.2d)), this.mPaint_date2);
                return;
            case 5:
                Paint paint29 = this.mPaintDigital_time_Hour;
                double d139 = (double) this.radius;
                Double.isNaN(d139);
                paint29.setTextSize((float) (d139 * 0.27d));
                Paint paint30 = this.mPaintDigital_time_Min;
                double d140 = (double) this.radius;
                Double.isNaN(d140);
                paint30.setTextSize((float) (d140 * 0.17d));
                Paint paint31 = this.mPaintDigital_time_Colon;
                double d141 = (double) this.radius;
                Double.isNaN(d141);
                paint31.setTextSize((float) (d141 * 0.07d));
                float f24 = this.f206x;
                this.Digital_time_Hours_X_offset = f24;
                float f25 = this.f207y;
                this.Digital_time_Hours_Y_offset = f25;
                double d142 = (double) f24;
                int i20 = this.radius;
                double d143 = (double) i20;
                Double.isNaN(d143);
                Double.isNaN(d142);
                float f26 = (float) (d142 + (d143 * 0.08d));
                this.Digital_time_Mintues_X_offset = f26;
                double d144 = (double) f25;
                double d145 = (double) i20;
                Double.isNaN(d145);
                Double.isNaN(d144);
                this.Digital_time_Mintues_Y_offset = (float) (d144 + (d145 * 0.18d));
                double d146 = (double) f26;
                double d147 = (double) i20;
                Double.isNaN(d147);
                Double.isNaN(d146);
                this.Digital_time_Colon_X_offset = (float) (d146 + (d147 * 0.2d));
                double d148 = (double) f25;
                double d149 = (double) i20;
                Double.isNaN(d149);
                Double.isNaN(d148);
                this.Digital_time_Colon_Y_offset = (float) (d148 + (d149 * 0.2d));
                canvas.drawText(this.used12hours, f24, f25, this.mPaintDigital_time_Hour);
                canvas.drawText(this.usedtwntymintues, this.Digital_time_Mintues_X_offset, this.Digital_time_Mintues_Y_offset, this.mPaintDigital_time_Min);
                Calendar_data();
                Paint paint32 = this.mPaint_date;
                double d150 = (double) this.radius;
                Double.isNaN(d150);
                paint32.setTextSize((float) (d150 * 0.07d));
                Paint paint33 = this.mPaint_date1;
                double d151 = (double) this.radius;
                Double.isNaN(d151);
                paint33.setTextSize((float) (d151 * 0.07d));
                Paint paint34 = this.mPaint_date2;
                double d152 = (double) this.radius;
                Double.isNaN(d152);
                paint34.setTextSize((float) (d152 * 0.07d));
                String str15 = this.usedweekday;
                double d153 = (double) this.f206x;
                int i21 = this.radius;
                double d154 = (double) i21;
                Double.isNaN(d154);
                Double.isNaN(d153);
                double d155 = (double) this.f207y;
                double d156 = (double) i21;
                Double.isNaN(d156);
                Double.isNaN(d155);
                canvas.drawText(str15, (float) (d153 - (d154 * 0.13d)), (float) (d155 + (d156 * 0.08d)), this.mPaint_date);
                String str16 = this.useddate;
                double d157 = (double) this.f206x;
                int i22 = this.radius;
                double d158 = (double) i22;
                Double.isNaN(d158);
                Double.isNaN(d157);
                double d159 = (double) this.f207y;
                double d160 = (double) i22;
                Double.isNaN(d160);
                Double.isNaN(d159);
                canvas.drawText(str16, (float) (d157 - (d158 * 0.13d)), (float) (d159 + (d160 * 0.17d)), this.mPaint_date1);
                return;
            case 6:
                Paint paint35 = this.mPaintDigital_time_Min;
                double d161 = (double) this.radius;
                Double.isNaN(d161);
                paint35.setTextSize((float) (d161 * 0.2d));
                Paint paint36 = this.mPaintDigital_time_Hour;
                double d162 = (double) this.radius;
                Double.isNaN(d162);
                paint36.setTextSize((float) (d162 * 0.2d));
                float f27 = this.f206x;
                double d163 = (double) f27;
                int i23 = this.radius;
                double d164 = (double) i23;
                Double.isNaN(d164);
                Double.isNaN(d163);
                float f28 = (float) (d163 - (d164 * 0.29d));
                this.Digital_time_Hours_X_offset = f28;
                float f29 = this.f207y;
                double d165 = (double) f29;
                double d166 = (double) i23;
                Double.isNaN(d166);
                Double.isNaN(d165);
                float f30 = (float) (d165 + (d166 * 0.13d));
                this.Digital_time_Hours_Y_offset = f30;
                this.Digital_time_Colon_X_offset = f27;
                double d167 = (double) f29;
                double d168 = (double) i23;
                Double.isNaN(d168);
                Double.isNaN(d167);
                this.Digital_time_Colon_Y_offset = (float) (d167 + (d168 * 0.13d));
                double d169 = (double) f27;
                double d170 = (double) i23;
                Double.isNaN(d170);
                Double.isNaN(d169);
                this.Digital_time_Mintues_X_offset = (float) (d169 + (d170 * 0.29d));
                double d171 = (double) f29;
                double d172 = (double) i23;
                Double.isNaN(d172);
                Double.isNaN(d171);
                this.Digital_time_Mintues_Y_offset = (float) (d171 + (d172 * 0.13d));
                canvas.drawText(this.used12hours, f28, f30, this.mPaintDigital_time_Hour);
                canvas.drawText(":", this.Digital_time_Colon_X_offset, this.Digital_time_Colon_Y_offset, this.mPaintDigital_time_Min);
                canvas.drawText(this.usedtwntymintues, this.Digital_time_Mintues_X_offset, this.Digital_time_Mintues_Y_offset, this.mPaintDigital_time_Min);
                Calendar_data();
                Paint paint37 = this.mPaint_date;
                double d173 = (double) this.radius;
                Double.isNaN(d173);
                paint37.setTextSize((float) (d173 * 0.1d));
                Paint paint38 = this.mPaint_date1;
                double d174 = (double) this.radius;
                Double.isNaN(d174);
                paint38.setTextSize((float) (d174 * 0.1d));
                Paint paint39 = this.mPaint_date2;
                double d175 = (double) this.radius;
                Double.isNaN(d175);
                paint39.setTextSize((float) (d175 * 0.1d));
                String str17 = this.usedweekday;
                double d176 = (double) this.f206x;
                int i24 = this.radius;
                double d177 = (double) i24;
                Double.isNaN(d177);
                Double.isNaN(d176);
                double d178 = (double) this.f207y;
                double d179 = (double) i24;
                Double.isNaN(d179);
                Double.isNaN(d178);
                canvas.drawText(str17, (float) (d176 - (d177 * 0.25d)), (float) (d178 - (d179 * 0.1d)), this.mPaint_date);
                String str18 = this.useddate;
                double d180 = (double) this.f206x;
                int i25 = this.radius;
                double d181 = (double) i25;
                Double.isNaN(d181);
                Double.isNaN(d180);
                double d182 = (double) this.f207y;
                double d183 = (double) i25;
                Double.isNaN(d183);
                Double.isNaN(d182);
                canvas.drawText(str18, (float) (d180 + (d181 * 0.15d)), (float) (d182 + (d183 * 0.3d)), this.mPaint_date1);
                String str19 = this.usedmonth;
                double d184 = (double) this.f206x;
                int i26 = this.radius;
                double d185 = (double) i26;
                Double.isNaN(d185);
                Double.isNaN(d184);
                double d186 = (double) this.f207y;
                double d187 = (double) i26;
                Double.isNaN(d187);
                Double.isNaN(d186);
                canvas.drawText(str19, (float) (d184 + (d185 * 0.39d)), (float) (d186 + (d187 * 0.3d)), this.mPaint_date2);
                return;
            case 7:
                Paint paint40 = this.mPaintDigital_time_Min;
                double d188 = (double) this.radius;
                Double.isNaN(d188);
                paint40.setTextSize((float) (d188 * 0.2d));
                Paint paint41 = this.mPaintDigital_time_Hour;
                double d189 = (double) this.radius;
                Double.isNaN(d189);
                paint41.setTextSize((float) (d189 * 0.2d));
                float f31 = this.f206x;
                double d190 = (double) f31;
                int i27 = this.radius;
                double d191 = (double) i27;
                Double.isNaN(d191);
                Double.isNaN(d190);
                float f32 = (float) (d190 - (d191 * 0.17d));
                this.Digital_time_Hours_X_offset = f32;
                float f33 = this.f207y;
                double d192 = (double) f33;
                double d193 = (double) i27;
                Double.isNaN(d193);
                Double.isNaN(d192);
                float f34 = (float) (d192 + (d193 * 0.13d));
                this.Digital_time_Hours_Y_offset = f34;
                this.Digital_time_Colon_X_offset = f31;
                double d194 = (double) f33;
                double d195 = (double) i27;
                Double.isNaN(d195);
                Double.isNaN(d194);
                this.Digital_time_Colon_Y_offset = (float) (d194 + (d195 * 0.13d));
                double d196 = (double) f31;
                double d197 = (double) i27;
                Double.isNaN(d197);
                Double.isNaN(d196);
                this.Digital_time_Mintues_X_offset = (float) (d196 + (d197 * 0.17d));
                double d198 = (double) f33;
                double d199 = (double) i27;
                Double.isNaN(d199);
                Double.isNaN(d198);
                this.Digital_time_Mintues_Y_offset = (float) (d198 + (d199 * 0.13d));
                canvas.drawText(this.used12hours, f32, f34, this.mPaintDigital_time_Hour);
                canvas.drawText(":", this.Digital_time_Colon_X_offset, this.Digital_time_Colon_Y_offset, this.mPaintDigital_time_Min);
                canvas.drawText(this.usedtwntymintues, this.Digital_time_Mintues_X_offset, this.Digital_time_Mintues_Y_offset, this.mPaintDigital_time_Min);
                Calendar_data();
                Paint paint42 = this.mPaint_date;
                double d200 = (double) this.radius;
                Double.isNaN(d200);
                paint42.setTextSize((float) (d200 * 0.1d));
                Paint paint43 = this.mPaint_date1;
                double d201 = (double) this.radius;
                Double.isNaN(d201);
                paint43.setTextSize((float) (d201 * 0.1d));
                Paint paint44 = this.mPaint_date2;
                double d202 = (double) this.radius;
                Double.isNaN(d202);
                paint44.setTextSize((float) (d202 * 0.1d));
                String str20 = this.usedweekday;
                double d203 = (double) this.f206x;
                int i28 = this.radius;
                double d204 = (double) i28;
                Double.isNaN(d204);
                Double.isNaN(d203);
                double d205 = (double) this.f207y;
                double d206 = (double) i28;
                Double.isNaN(d206);
                Double.isNaN(d205);
                canvas.drawText(str20, (float) (d203 - (d204 * 0.3d)), (float) (d205 - (d206 * 0.1d)), this.mPaint_date);
                String str21 = this.useddate;
                double d207 = (double) this.f206x;
                int i29 = this.radius;
                double d208 = (double) i29;
                Double.isNaN(d208);
                Double.isNaN(d207);
                double d209 = (double) this.f207y;
                double d210 = (double) i29;
                Double.isNaN(d210);
                Double.isNaN(d209);
                canvas.drawText(str21, (float) (d207 - (d208 * 0.14d)), (float) (d209 - (d210 * 0.1d)), this.mPaint_date1);
                String str22 = this.usedmonth;
                double d211 = (double) this.f206x;
                int i30 = this.radius;
                double d212 = (double) i30;
                Double.isNaN(d212);
                Double.isNaN(d211);
                double d213 = (double) this.f207y;
                double d214 = (double) i30;
                Double.isNaN(d214);
                Double.isNaN(d213);
                canvas.drawText(str22, (float) (d211 + (d212 * 0.0d)), (float) (d213 - (d214 * 0.1d)), this.mPaint_date2);
                return;
            case 8:
                Paint paint45 = this.mPaintDigital_time_Min;
                double d215 = (double) this.radius;
                Double.isNaN(d215);
                paint45.setTextSize((float) (d215 * 0.25d));
                Paint paint46 = this.mPaintDigital_time_Hour;
                double d216 = (double) this.radius;
                Double.isNaN(d216);
                paint46.setTextSize((float) (d216 * 0.28d));
                Paint paint47 = this.mPaintDigital_time_Colon;
                double d217 = (double) this.radius;
                Double.isNaN(d217);
                paint47.setTextSize((float) (d217 * 0.07d));
                float f35 = this.f206x;
                double d218 = (double) f35;
                int i31 = this.radius;
                double d219 = (double) i31;
                Double.isNaN(d219);
                Double.isNaN(d218);
                this.Digital_time_Hours_X_offset = (float) (d218 - (d219 * 0.17d));
                float f36 = this.f207y;
                double d220 = (double) f36;
                double d221 = (double) i31;
                Double.isNaN(d221);
                Double.isNaN(d220);
                this.Digital_time_Hours_Y_offset = (float) (d220 + (d221 * 0.13d));
                double d222 = (double) f35;
                double d223 = (double) i31;
                Double.isNaN(d223);
                Double.isNaN(d222);
                float f37 = (float) (d222 + (d223 * 0.15d));
                this.Digital_time_Mintues_X_offset = f37;
                double d224 = (double) f36;
                double d225 = (double) i31;
                Double.isNaN(d225);
                Double.isNaN(d224);
                this.Digital_time_Mintues_Y_offset = (float) (d224 + (d225 * 0.12d));
                double d226 = (double) f37;
                double d227 = (double) i31;
                Double.isNaN(d227);
                Double.isNaN(d226);
                this.Digital_time_Colon_X_offset = (float) (d226 + (d227 * 0.25d));
                double d228 = (double) f36;
                double d229 = (double) i31;
                Double.isNaN(d229);
                Double.isNaN(d228);
                this.Digital_time_Colon_Y_offset = (float) (d228 + (d229 * 0.05d));
                canvas.drawText(this.mCalendar.get(9) == 0 ? "AM" : "PM", this.Digital_time_Colon_X_offset, this.Digital_time_Colon_Y_offset, this.mPaintDigital_time_Colon);
                canvas.drawText(this.usedtwntymintues, this.Digital_time_Mintues_X_offset, this.Digital_time_Mintues_Y_offset, this.mPaintDigital_time_Min);
                canvas.drawText(this.used12hours, this.Digital_time_Hours_X_offset, this.Digital_time_Hours_Y_offset, this.mPaintDigital_time_Hour);
                Calendar_data();
                Paint paint48 = this.mPaint_date;
                double d230 = (double) this.radius;
                Double.isNaN(d230);
                paint48.setTextSize((float) (d230 * 0.05d));
                Paint paint49 = this.mPaint_date1;
                double d231 = (double) this.radius;
                Double.isNaN(d231);
                paint49.setTextSize((float) (d231 * 0.07d));
                Paint paint50 = this.mPaint_date2;
                double d232 = (double) this.radius;
                Double.isNaN(d232);
                paint50.setTextSize((float) (d232 * 0.07d));
                String str23 = this.usedweekday;
                double d233 = (double) this.f206x;
                int i32 = this.radius;
                double d234 = (double) i32;
                Double.isNaN(d234);
                Double.isNaN(d233);
                double d235 = (double) this.f207y;
                double d236 = (double) i32;
                Double.isNaN(d236);
                Double.isNaN(d235);
                canvas.drawText(str23, (float) (d233 - (d234 * 0.07d)), (float) (d235 + (d236 * 0.22d)), this.mPaint_date);
                String str24 = this.useddate;
                double d237 = (double) this.f206x;
                int i33 = this.radius;
                double d238 = (double) i33;
                Double.isNaN(d238);
                Double.isNaN(d237);
                double d239 = (double) this.f207y;
                double d240 = (double) i33;
                Double.isNaN(d240);
                Double.isNaN(d239);
                canvas.drawText(str24, (float) (d237 + (d238 * 0.05d)), (float) (d239 + (d240 * 0.22d)), this.mPaint_date1);
                String str25 = this.usedmonth;
                double d241 = (double) this.f206x;
                int i34 = this.radius;
                double d242 = (double) i34;
                Double.isNaN(d242);
                Double.isNaN(d241);
                double d243 = (double) this.f207y;
                double d244 = (double) i34;
                Double.isNaN(d244);
                Double.isNaN(d243);
                canvas.drawText(str25, (float) (d241 + (d242 * 0.18d)), (float) (d243 + (d244 * 0.22d)), this.mPaint_date2);
                return;
            case 9:
                Paint paint51 = this.mPaintDigital_time_Hour;
                double d245 = (double) this.radius;
                Double.isNaN(d245);
                paint51.setTextSize((float) (d245 * 0.25d));
                Paint paint52 = this.mPaintDigital_time_Min;
                double d246 = (double) this.radius;
                Double.isNaN(d246);
                paint52.setTextSize((float) (d246 * 0.25d));
                Paint paint53 = this.mPaintDigital_time_Colon;
                double d247 = (double) this.radius;
                Double.isNaN(d247);
                paint53.setTextSize((float) (d247 * 0.07d));
                float f38 = this.f206x;
                this.Digital_time_Hours_X_offset = f38;
                float f39 = this.f207y;
                double d248 = (double) f39;
                int i35 = this.radius;
                double d249 = (double) i35;
                Double.isNaN(d249);
                Double.isNaN(d248);
                float f40 = (float) (d248 + (d249 * 0.05d));
                this.Digital_time_Hours_Y_offset = f40;
                this.Digital_time_Mintues_X_offset = f38;
                double d250 = (double) f39;
                double d251 = (double) i35;
                Double.isNaN(d251);
                Double.isNaN(d250);
                this.Digital_time_Mintues_Y_offset = (float) (d250 + (d251 * 0.29d));
                double d252 = (double) f38;
                double d253 = (double) i35;
                Double.isNaN(d253);
                Double.isNaN(d252);
                this.Digital_time_Colon_X_offset = (float) (d252 + (d253 * 0.2d));
                double d254 = (double) f39;
                double d255 = (double) i35;
                Double.isNaN(d255);
                Double.isNaN(d254);
                this.Digital_time_Colon_Y_offset = (float) (d254 + (d255 * 0.05d));
                canvas.drawText(this.used12hours, f38, f40, this.mPaintDigital_time_Hour);
                canvas.drawText(this.usedtwntymintues, this.Digital_time_Mintues_X_offset, this.Digital_time_Mintues_Y_offset, this.mPaintDigital_time_Min);
                Calendar_data();
                Paint paint54 = this.mPaint_date;
                double d256 = (double) this.radius;
                Double.isNaN(d256);
                paint54.setTextSize((float) (d256 * 0.1d));
                Paint paint55 = this.mPaint_date1;
                double d257 = (double) this.radius;
                Double.isNaN(d257);
                paint55.setTextSize((float) (d257 * 0.1d));
                Paint paint56 = this.mPaint_date2;
                double d258 = (double) this.radius;
                Double.isNaN(d258);
                paint56.setTextSize((float) (d258 * 0.1d));
                String str26 = this.useddate;
                double d259 = (double) this.f206x;
                int i36 = this.radius;
                double d260 = (double) i36;
                Double.isNaN(d260);
                Double.isNaN(d259);
                double d261 = (double) this.f207y;
                double d262 = (double) i36;
                Double.isNaN(d262);
                Double.isNaN(d261);
                canvas.drawText(str26, (float) (d259 - (d260 * 0.07d)), (float) (d261 + (d262 * 0.4d)), this.mPaint_date1);
                String str27 = this.usedmonth;
                double d263 = (double) this.f206x;
                int i37 = this.radius;
                double d264 = (double) i37;
                Double.isNaN(d264);
                Double.isNaN(d263);
                double d265 = (double) this.f207y;
                double d266 = (double) i37;
                Double.isNaN(d266);
                Double.isNaN(d265);
                canvas.drawText(str27, (float) (d263 + (d264 * 0.06d)), (float) (d265 + (d266 * 0.4d)), this.mPaint_date2);
                return;
            default:
                return;
        }
    }

    private void Calendar_data() {
        Date time = Calendar.getInstance().getTime();
        Calendar instance = Calendar.getInstance();
        instance.setTime(time);
        String[] split = new SimpleDateFormat("yyyy-MMM-dd").format(time).split("-");
        this.useddate = split[2];
        this.usedmonth = split[1].toUpperCase();
        this.usedweekday = this.stringsDays[instance.get(7) - 1];
    }

    public void setTextFace() {
        switch (this.textClockPosition) {
            case 0:
                this.mPaint_date.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "montserrat_semi_bold.ttf"));
                this.mPaint_date1.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "montserrat_light.ttf"));
                this.mPaint_date2.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "montserrat_light.ttf"));
                this.mPaintDigital_time_Hour.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "montserrat_semi_bold.ttf"));
                this.mPaintDigital_time_Min.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "montserrat_light.ttf"));
                this.mPaintDigital_time_Colon.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "montserrat_light.ttf"));
                return;
            case 1:
                this.mPaint_date.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "montserrat_semi_bold.ttf"));
                this.mPaint_date1.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "montserrat_light.ttf"));
                this.mPaint_date2.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "montserrat_light.ttf"));
                this.mPaintDigital_time_Hour.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "rubik_variablefont_wght.ttf"));
                this.mPaintDigital_time_Min.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "rubik_variablefont_wght.ttf"));
                this.mPaintDigital_time_Colon.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "rubik_variablefont_wght.ttf"));
                return;
            case 2:
                this.mPaint_date.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "open_sans_bold.ttf"));
                this.mPaint_date1.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "open_sans_bold.ttf"));
                this.mPaint_date2.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "open_sans_bold.ttf"));
                this.mPaintDigital_time_Hour.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "tokarev.ttf"));
                this.mPaintDigital_time_Min.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "tokarev.ttf"));
                this.mPaintDigital_time_Colon.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "rubik_variablefont_wght.ttf"));
                return;
            case 3:
                this.mPaint_date.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "pathwaygothicone_regular.ttf"));
                this.mPaint_date1.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "montserrat_light.ttf"));
                this.mPaint_date2.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "montserrat_light.ttf"));
                this.mPaintDigital_time_Hour.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "oswald_variable_font_wght.ttf"));
                this.mPaintDigital_time_Min.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "oswald_variable_font_wght.ttf"));
                this.mPaintDigital_time_Colon.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "rubik_variablefont_wght.ttf"));
                return;
            case 4:
                this.mPaint_date.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "rubik_variablefont_wght.ttf"));
                this.mPaint_date1.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "rubik_variablefont_wght.ttf"));
                this.mPaint_date2.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "rubik_variablefont_wght.ttf"));
                this.mPaintDigital_time_Hour.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "open_sans_regular.ttf"));
                this.mPaintDigital_time_Min.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "open_sans_regular.ttf"));
                this.mPaintDigital_time_Colon.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "open_sans_regular.ttf"));
                this.mPaintDigital_time_Colon.setStrokeWidth(12.0f);
                return;
            case 5:
                this.mPaint_date.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "jetbrains_mono_medium.ttf"));
                this.mPaint_date1.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "jetbrains_mono_medium.ttf"));
                this.mPaint_date2.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "jetbrains_mono_medium.ttf"));
                this.mPaintDigital_time_Hour.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "DelaGothicOne-Regular.ttf"));
                this.mPaintDigital_time_Min.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "DelaGothicOne-Regular.ttf"));
                this.mPaintDigital_time_Colon.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "rubik_variablefont_wght.ttf"));
                return;
            case 6:
                this.mPaint_date.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "bungee_shade_regular.ttf"));
                this.mPaint_date1.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "bungee_shade_regular.ttf"));
                this.mPaint_date2.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "bungee_shade_regular.ttf"));
                this.mPaintDigital_time_Hour.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "bungee_shade_regular.ttf"));
                this.mPaintDigital_time_Min.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "bungee_shade_regular.ttf"));
                this.mPaintDigital_time_Colon.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "bungee_shade_regular.ttf"));
                return;
            case 7:
                this.mPaint_date.setColor(this.color2);
                this.mPaint_date.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "oswald_variable_font_wght.ttf"));
                this.mPaint_date1.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "oswald_variable_font_wght.ttf"));
                this.mPaint_date2.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "oswald_variable_font_wght.ttf"));
                this.mPaintDigital_time_Hour.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "oswald_variable_font_wght.ttf"));
                this.mPaintDigital_time_Min.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "oswald_variable_font_wght.ttf"));
                this.mPaintDigital_time_Colon.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "oswald_variable_font_wght.ttf"));
                return;
            case 8:
                this.mPaint_date.setColor(this.color2);
                this.mPaint_date.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "open_sans_light.ttf"));
                this.mPaint_date1.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "open_sans_light.ttf"));
                this.mPaint_date2.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "open_sans_light.ttf"));
                this.mPaintDigital_time_Hour.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "open_sans_light.ttf"));
                this.mPaintDigital_time_Min.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "open_sans_light.ttf"));
                this.mPaintDigital_time_Colon.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "open_sans_light.ttf"));
                return;
            case 9:
                this.mPaint_date.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "bigshoulders_stencil_display_regular.ttf"));
                this.mPaint_date1.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "bigshoulders_stencil_display_regular.ttf"));
                this.mPaint_date2.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "bigshoulders_stencil_display_regular.ttf"));
                this.mPaintDigital_time_Hour.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "bigshoulders_stencil_display_regular.ttf"));
                this.mPaintDigital_time_Min.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "bigshoulders_stencil_display_regular.ttf"));
                this.mPaintDigital_time_Colon.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "bigshoulders_stencil_display_regular.ttf"));
                return;
            default:
                return;
        }
    }

    public void setColors(int i, int i2) {
        this.color1 = i;
        this.color2 = i2;
        init();
        invalidate();
    }
}
