#!/usr/bin/env python3
"""Build the downloadable Android Studio package for this project.

    python3 tools/build_package.py [output.zip]

Default output: <repo root>/Allah-Clock-Live-Wallpaper-android-studio.zip

The package is the project exactly as Android Studio needs it - the app module, the Gradle
wrapper and build scripts, the docs, and the Python/Node verification tools. Deliberately
excluded:

  * .git                      - the user clones or downloads, they do not need history
  * any build/ or .gradle/    - generated by the first Gradle sync
  * tools/preview/assets/     - generated by tools/preview/build_assets.py (3.5 MB)
  * local.properties          - machine specific, and gitignored anyway
  * any *.zip                 - so a served copy of this package cannot nest inside itself

gradlew keeps its executable bit inside the archive, so ./gradlew works on macOS and Linux
straight after unzipping.
"""
import os
import sys
import zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_NAME = 'Allah-Clock-Live-Wallpaper-android-studio.zip'

# Directories included wholesale (minus the generated paths filtered below).
INCLUDE_DIRS = ('app', 'gradle', 'tools', 'docs')
# Root-level files included as-is.
INCLUDE_FILES = ('build.gradle', 'settings.gradle', 'gradle.properties', 'gradlew', 'gradlew.bat',
                 'UPGRADE_NOTES.md', '.gitignore')
# Directory names never packaged.
SKIP_DIRS = ('build', '.gradle', '.git', '__pycache__', 'node_modules')
# Generated preview assets live under tools/preview/assets.
SKIP_SUBTREES = (('tools', 'preview', 'assets'),)
# Never nest an archive inside itself: a copy of this package may sit in tools/preview/ so the
# live mock server can serve it over HTTP, and rebuilds must ignore it.
SKIP_SUFFIXES = ('.zip',)


def skipped_subtree(top, rel_parts):
    """True when this directory is a generated subtree listed in SKIP_SUBTREES."""
    for prefix in SKIP_SUBTREES:
        if (top,) + rel_parts[:len(prefix) - 1] == prefix:
            return True
    return False


def collect():
    """Yield (absolute path, archive path) pairs in a stable order."""
    entries = []
    for name in INCLUDE_FILES:
        full = os.path.join(ROOT, name)
        if os.path.isfile(full):
            entries.append((full, name))
    for top in INCLUDE_DIRS:
        base = os.path.join(ROOT, top)
        if not os.path.isdir(base):
            continue
        for dirpath, dirnames, filenames in os.walk(base):
            rel_parts = os.path.relpath(dirpath, base).split(os.sep)
            rel_parts = () if rel_parts == [''] else tuple(rel_parts)
            if skipped_subtree(top, rel_parts):
                dirnames[:] = []
                continue
            dirnames[:] = sorted(d for d in dirnames if d not in SKIP_DIRS)
            for filename in sorted(filenames):
                if filename.endswith(SKIP_SUFFIXES):
                    continue
                full = os.path.join(dirpath, filename)
                entries.append((full, os.path.relpath(full, ROOT)))
    return entries


def main(argv):
    out = os.path.abspath(argv[1]) if len(argv) > 1 else os.path.join(ROOT, DEFAULT_NAME)
    entries = collect()
    with zipfile.ZipFile(out, 'w', zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        for full, arcname in entries:
            archive.write(full, arcname)
    size_mb = os.path.getsize(out) / (1024 * 1024)
    print('%s: %d files, %.2f MB' % (out, len(entries), size_mb))
    for probe in ('gradlew', 'settings.gradle', 'app/build.gradle',
                  'app/src/main/AndroidManifest.xml', 'docs/ANDROID_STUDIO_SETUP.md',
                  'docs/QURAN_TEXT_ATTRIBUTION.md',
                  'app/src/main/res/raw/quran_uthmani.txt',
                  'app/src/main/res/raw/quran_pages.tsv',
                  'app/src/main/res/raw/quran_juz.tsv',
                  'app/src/main/java/org/Allah_Clock_Live_Wallpaper/activity/QuranIndexActivity.java',
                  'app/src/main/java/org/Allah_Clock_Live_Wallpaper/activity/QuranMushafActivity.java'):
        if probe not in {a for _, a in entries}:
            print('WARNING: expected %s in the package' % probe)
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
